Kernel360/f1-JDON-Backend

module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/service/FaqService.java, module-common/build.gradle, module-common/src/main/java/kernel/jdon/modulecommon/error/code/ErrorCode.java, module-common/src/main/java/kernel/jdon/modulecommon/error/code/FaqErrorCode.java, module-common/src/main/java/kernel/jdon/modulecommon/error/exception/api/ApiException.java
- module-common
- ErrorCode 및 ApiException 구현
- FaqErrorCode 구현
- build.gradle 
- spring-boot-starter-web 의존성 추가
- module-common은 jar 파일이 필요 없기 때문에 아래 설정부분 추가
```
jar {
enabled = true
}
```
- module-api
- FaqErrorCode 적용
- module-common
- 도메인 별 ErrorCode(ex.FaqErrorCode)에서 HTTPStatus 클래스를 필요로하여 spring-boot-starter-web 의존성 추가하였습니다.
- ErrorCode interface 및 module-api 모듈에서만 사용하는 RuntimeException을 상속받은 ApiException을 생성하였습니다.
- 구현된 FAQ 도메인에서 사용할 FaqErrorCode를 생성하였습니다.
- module-api
- 기존 임시로 적용했던 IllegalArgumentException을 제거하고 FaqErrorCode를 적용함에 따라 FaqService, FaqServiceTest를 수정하였습니다.
- closes: #31
---
어떤 변경 사항이 있나요?
=> Feature: ErrorCode, FaqErrorCode 생성 및 적용

module-api/src/test/java/kernel/jdon/moduleapi/domain/faq/service/FaqServiceTest.java, module-domain/src/main/java/kernel/jdon/faq/dto/response/FindFaqResponse.java
faq 목록 조회 API의 응답에 faqId를 추가하였습니다. 
- FindFaqResponse 에 faqId 필드를 추가했습니다. 
- FaqServiceTest에 id를 확인하는 코드를 추가했습니다. 
이제 faq 목록 조회를 하면 id, title, content가 같이 옵니다. 
- closes: #39 
---
어떤 변경 사항이 있나요?
=> Fix: Add faqId at FindFaqListResponse

build.gradle, module-api/build.gradle, module-api/settings.gradle, module-common/build.gradle, module-common/settings.gradle, module-domain/build.gradle, module-domain/settings.gradle
- jdk 17로 변경
- 하위 모듈들에서 settings.gradle 삭제
- 수동 빌드 시 gradle과 jdk 21이 호환되지 않아 jdk 17로 다운 그레이션 진행
- Project Structure 에서 project setting내 SDK를 17로 변경이 필요합니다. 
- 모든 build.gradle 파일에서 sourceCompatibility 를 17로 수정했습니다.
- root module이 아닌 하위 module에 settings.gradle 파일이 있으면 빌드시에 오류가 발생하여 삭제
- closes: #41 
---
어떤 변경 사항이 있나요?
=> Chore: jdk 버전 변경(21 -> 17) 및 하위 모듈 settings.gradle 파일 삭제

module-api/build.gradle
api 모듈 빌드시 plain.jar 생성하지 않도록 build.gradle 수정
plain.jar를 생성하지 않도록 tasks.jar를 false로 변경했습니다.
실행가능한 jar 파일을 생성하는 bootJar옵션은 디폴트가 true이나 명시적으로 추가했습니다
moudle-api내 build.gradle
빌드시 plain.jar를 더 이상 생성하지 않고 .jar 파일만 생성
- closes: #47 
---
어떤 변경 사항이 있나요?
=> Chore: module-api 빌드설정 수정(plain.jar 생성X)

module-api/src/main/resources/application.yml, module-api/src/main/resources/logback-spring.xml, module-common/build.gradle, module-domain/build.gradle
- logback-spring.xml 추가
- common, domain 모듈 build.gradle에 prepareKotlinBuildScriptModel 옵션 추가
- module-api에 logback-spring.xml을 생성하고 application.yml 파일에서 로그레벨을 info로 설정했습니다.
- module-common, module-domain 빌드 시 다음과 같은 에러가 발생했습니다.
프로젝트에서 Kotlin 코드를 포함하고 있지 않기 때문에 tasks.register("prepareKotlinBuildScriptModel") {} 을 설정하여 정상빌드 되도록 변경했습니다.
- closes: #45 
---
어떤 변경 사항이 있나요?
=> Feature: api모듈 logback 적용 및 common, domain 모듈 prepareKotlinBuildScriptModel 적용

module-domain/src/main/java/kernel/jdon/member/domain/Member.java
Member entity 수정
- `nickname`, `email` 필드에 `unique=true` 옵션이 누락되어 추가했습니다.
- 어느 경로에서 `소셜 회원가입`을 했는지 `식별`할 수 있는 `social_provider` 컬럼 추가했습니다.
- 설계 단계에서 폼 로그인 기능이 삭제되어 불필요한 컬럼인 `password` `제거`했습니다.
- closes: #49 
---
어떤 변경 사항이 있나요?
=> Fix: 폼 로그인 설계 변경으로 인한 Member 엔티티 수정

module-domain/src/main/java/kernel/jdon/config/JpaAuditingConfig.java
- config/JpaAuditingConfig.java 파일 및 패키지의 모듈 위치 변경
- module-common에 위치한 config 패키지를 특정 모듈에서 사용하는 config 별로 분리하였습니다.
- module-common에 위치한 JpaAuditingConfig 파일은 module-domain에 종속된 config 파일이기 때문에 module-domain으로 config 패키지 생성 후 이동 시켰습니다.
- closes: #57 
---
어떤 변경 사항이 있나요?
=> Chore: 모듈 별 config 파일 이동

module-domain/src/main/java/kernel/jdon/jobcategory/domain/JobCategory.java, module-domain/src/main/java/kernel/jdon/skill/domain/Skill.java
- skill 테이블 count컬럼 추가
- job_category 테이블 name 컬럼 unique 제약조건 추가
- 원티드에서 추출한 skill의 빈도 수를 확인하기 위한 skill 테이블 count컬럼 추가
- 직무, 직군 데이터를 저장하는 job_category 테이블 name 컬럼에 unique 제약조건 추가
- closes: #62 
---
어떤 변경 사항이 있나요?
=> BugFix: skill, job_category 테이블 수정

module-common/src/main/java/kernel/jdon/util/StringUtil.java, module-crawler/src/main/java/kernel/jdon/config/AppConfig.java, module-crawler/src/main/java/kernel/jdon/config/UrlConfig.java, module-crawler/src/main/java/kernel/jdon/crawler/wanted/controller/WantedCrawlerController.java, module-crawler/src/main/java/kernel/jdon/crawler/wanted/converter/EntityConverter.java, module-crawler/src/main/java/kernel/jdon/crawler/wanted/converter/EntityFactory.java, module-crawler/src/main/java/kernel/jdon/crawler/wanted/dto/object/CreateSkillDto.java, module-crawler/src/main/java/kernel/jdon/crawler/wanted/dto/response/WantedJobDetailResponse.java, module-crawler/src/main/java/kernel/jdon/crawler/wanted/dto/response/WantedJobListResponse.java, module-crawler/src/main/java/kernel/jdon/crawler/wanted/repository/JobCategoryRepository.java, module-crawler/src/main/java/kernel/jdon/crawler/wanted/repository/SkillRepository.java, module-crawler/src/main/java/kernel/jdon/crawler/wanted/repository/WantedJdRepository.java, module-crawler/src/main/java/kernel/jdon/crawler/wanted/repository/WantedJdSkillRepository.java, module-crawler/src/main/java/kernel/jdon/crawler/wanted/search/JobSearchCondition.java, module-crawler/src/main/java/kernel/jdon/crawler/wanted/search/JobSearchExperience.java, module-crawler/src/main/java/kernel/jdon/crawler/wanted/search/JobSearchJobCategory.java, module-crawler/src/main/java/kernel/jdon/crawler/wanted/search/JobSearchJobPosition.java, module-crawler/src/main/java/kernel/jdon/crawler/wanted/search/JobSearchLocation.java, module-crawler/src/main/java/kernel/jdon/crawler/wanted/search/JobSearchSort.java, module-crawler/src/main/java/kernel/jdon/crawler/wanted/service/WantedCrawlerService.java, module-crawler/src/main/java/kernel/jdon/crawler/wanted/vo/SkillVo.java, module-crawler/src/main/resources/url.properties, module-domain/src/main/java/kernel/jdon/jobcategory/domain/JobCategory.java, module-domain/src/main/java/kernel/jdon/skill/domain/Skill.java, module-domain/src/main/java/kernel/jdon/wanted/domain/WantedJd.java, module-domain/src/main/java/kernel/jdon/wantedskill/domain/WantedJdSkill.java
- 원티드 채용공고 조회 api를 스크래핑 해와서 JD 목록을 추출
- 상세 JD의 내용, 기술스택을 추출
- StringUtil 클래스 생성
- Controller, Service, Repository 생성
- 구현하면서 수동으로 API를 호출해서 스크래핑 정상 작동 유무를 테스트하기 위해 테스트 API를 구현해두었습니다. 추후 스케줄링 방식으로 리팩토링 할 예정입니다.
- Service 또한 리팩토링 시 패키지구조 및 클래스명을 어떠한 방향으로 가져갈지 상의해야합니다.
- Repository는 module-crawler에서 해당 엔티티를 접근하기위한 객체로, 추후 리팩토링 시 변경사항 없습니다.
- WantedCrawlerService 클래스
- **기능 위주로 절차지향으로 구현된 코드로 추후 리팩토링이 필요합니다 !!!**
- dto 패키지 생성
- dto/object 패키지 : 메서드 내 파라미터가 많아져 메서드 간의 이동을 위한 클래스를 보관하는 패키지
- dto/response 패키지 : 원티드 api에서 스크래핑하여 응답받은 객체를 저장하는 패키지
- DTO 및 객체를 엔티티로 형변환하는 역할을 담당하는 EntityFactory 생성
- 쿼리파라미터를 생성할 때 원티드 검색조건을 관리할 수 있는 interface를 생성
- JobSearchCondition
- JobSearchCondition을 구현한 각각의 enum class를 생성
- JobSearchExperience : 경력 검색조건
- JobSearchJobCategory : 직군 검색조건
- JobSearchJobPosition : …
=> Feature: 원티드 jd 스크래핑 구현

module-api/src/main/java/kernel/jdon/skill/controller/SkillController.java, module-api/src/test/resources/application.yml, module-domain/src/main/java/kernel/jdon/skill/dto/FindHotSkillResponse.java, module-domain/src/main/java/kernel/jdon/skill/dto/FindJdResponse.java, module-domain/src/main/java/kernel/jdon/skill/dto/FindJobCategorySkillResponse.java, module-domain/src/main/java/kernel/jdon/skill/dto/FindLectureResponse.java, module-domain/src/main/java/kernel/jdon/skill/dto/FindListDataBySkillResponse.java, module-domain/src/main/java/kernel/jdon/skill/dto/FindListHotSkillResponse.java, module-domain/src/main/java/kernel/jdon/skill/dto/FindListJobCategorySkillResponse.java, module-domain/src/main/java/kernel/jdon/skill/dto/FindListMemberSkillResponse.java, module-domain/src/main/java/kernel/jdon/skill/dto/FindMemberSkillResponse.java
- 가데이터를 반환하는 Skill 관련 API 구현
- 프론트엔드 요청에 따라 API 명세서 규격에 맞는 요청받고 데이터를 응답하도록 API를 구현하였습니다.
- 요즘 뜨는 기술 스택 조회 API : https://www.notion.so/6bb63a7d4c034e4fba1062f0f0b1f12e?pvs=4
- 회원 맞춤 기술 스택 조회 API : https://www.notion.so/a6f53af68e9844c8a83c3e24b742a0d9?pvs=4
- 기술 스택에 맞는 강의 및 JD 조회 API : https://www.notion.so/52bfd0c650d34a929f5e76884f93e065?pvs=4
- 직군별 기술 스택 조회 API : https://www.notion.so/d7734d2eeb364296b7aaf66a1b06bb3e?pvs=4
- /api/v1/skills/hot
- /api/v1/skills/member
- /api/v1/skills/search?keyword={keyword}
- /api/v1/skills/job-category/{jobCategoryId}
- closes: #67 
---
어떤 변경 사항이 있나요?
=> Feature: 가데이터 반환 Skill API 구현

module-domain/src/main/java/kernel/jdon/wanted/domain/WantedJd.java
- WantedJd 엔티티 복합 유니크키 설정
원티드에서 같은 공고를 프론트엔드, 서버개발자 공고로 이중 설정 할 수 있기 때문에 기존과 같이 원티드 공고 식별자 컬럼만 유니크키로 설정했을 때 sql 에러가 발생합니다.
따라서, 직군, 원티드 공고 식별자를 복합 유니크키로 설정했습니다.
- 기존 WantedJd 엔티티 detail_id 컬럼 유니크 제약조건 제거
- 기존 WantedJd 엔티티 detail_id 컬럼, job_category_id 컬럼을 복합 유니크 키로 설정
- closes: #78 
---
어떤 변경 사항이 있나요?
=> fix: WantedJd 엔티티 복합 유니크키 설정

module-crawler/src/main/java/kernel/jdon/crawler/wanted/converter/EntityConverter.java, module-crawler/src/main/java/kernel/jdon/crawler/wanted/dto/response/WantedJobDetailResponse.java, module-crawler/src/main/java/kernel/jdon/crawler/wanted/service/WantedCrawlerService.java, module-domain/src/main/java/kernel/jdon/wanted/domain/WantedJd.java
- wanted 엔티티 누락 컬럼 추가
- 스크래핑 일자, 원티드 jd의 제목 컬럼 추가 하였습니다.
- 원티드 공고 스크래핑 시 스크래핑 및 원티드 jd의 제목 데이터를 저장하도록 수정하였습니다.
- 아래와 같이 금일 스크래핑한 원티드 데이터부터 스크래핑 일자, 원티드 jd의 제목 컬럼에 데이터가 들어가는 것을 확인하였습니다.
- closes: #80 
---
어떤 변경 사항이 있나요?
=> BugFix: add column title, scrapingDate at WantedJd table

module-api/src/main/java/kernel/jdon/coffeechat/controller/CoffeeChatController.java, module-api/src/main/java/kernel/jdon/coffeechat/repository/CoffeeChatRepository.java, module-api/src/main/java/kernel/jdon/coffeechat/service/CoffeeChatService.java, module-common/src/main/java/kernel/jdon/error/code/CoffeeChatErrorCode.java, module-domain/src/main/java/kernel/jdon/coffeechat/domain/CoffeeChat.java, module-domain/src/main/java/kernel/jdon/coffeechat/dto/request/CreateCoffeeChatRequest.java, module-domain/src/main/java/kernel/jdon/coffeechat/dto/response/CreateCoffeeChatResponse.java, module-domain/src/main/java/kernel/jdon/coffeechat/dto/response/FindCoffeeChatResponse.java, module-domain/src/main/java/kernel/jdon/member/domain/Member.java
커피챗 등록과 상세조회 API를 구현했습니다.
- Member 엔터티 변경
- CoffeChat 엔터티 변경 및 API별 DTO 생성
- CoffeChat Controller, Service, Repository 생성
- Member
- 엔터티에 생성자를 만들고 빌더어노테이션 적용
- CoffeeChat
- 엔터티에서 디폴트값 필요한 항목들 적용
- 등록, 상세조회에 필요한 DTO 작성
- 커스텀 익셉션에 담을 에러코드 Enum 생성
- Controller, Service, Repository 작성
- closes: #92 
---
어떤 변경 사항이 있나요?
=> Feature: 커피챗 등록, 상세조회 API 구현

module-api/src/main/java/kernel/jdon/favorite/controller/FavoriteController.java, module-domain/src/main/java/kernel/jdon/favorite/domain/dto/request/CreateFavoriteRequest.java, module-domain/src/main/java/kernel/jdon/favorite/domain/dto/request/SaveFavoriteRequest.java, module-domain/src/main/java/kernel/jdon/favorite/domain/dto/response/CreateFavoriteResponse.java, module-domain/src/main/java/kernel/jdon/favorite/domain/dto/response/FindFavoriteResponse.java, module-domain/src/main/java/kernel/jdon/favorite/domain/dto/response/SaveFavoriteResponse.java
- 가데이터를 반환하는 Skill 관련 API 구현
- 프론트엔드 요청에 따라 API 명세서 규격에 맞는 요청받고 데이터를 응답하도록 API를 구현하였습니다.
- 내가 찜한 영상 목록 조회하기 API : https://www.notion.so/a54d5635404a4dfd8b79d7561e5b80d6
- 영상 찜하는 버튼 누르기 API : https://www.notion.so/API-d0b2b8e78dd142ca8ace674e8d4a5705
- /api/v1/favorites
- /api/v1/favorites
- closes: #69 
---
어떤 변경 사항이 있나요?
=> Feature: add dummy data for favorite inflearn lecture api

module-api/src/main/java/kernel/jdon/skill/controller/SkillController.java, module-domain/src/main/java/kernel/jdon/skill/dto/FindCompanyBySkillResponse.java, module-domain/src/main/java/kernel/jdon/skill/dto/FindListCompanyBySkillResponse.java
- 가데이터를 변환하는 Skill 관련 API 구현
- 프론트엔드 요청에 따라 API 명세서 규격에 맞는 요청받고 데이터를 응답하도록 API를 구현하였습니다.
- 기술 스택에 따른 회사 조회하기 API : https://www.notion.so/d579cc615f4a4facae5a5760edd64454
- closes: #111 
---
어떤 변경 사항이 있나요?
=> Feature: add dummy data for finding companies by skill api

module-api/src/main/java/kernel/jdon/coffeechat/controller/CoffeeChatController.java, module-api/src/main/java/kernel/jdon/coffeechat/repository/CoffeeChatRepository.java, module-api/src/main/java/kernel/jdon/coffeechat/service/CoffeeChatService.java, module-domain/src/main/java/kernel/jdon/coffeechat/domain/CoffeeChat.java
커피챗 삭제 API를 구현했습니다(Soft Delete)
커피챗 단건 조회시 삭제여부를 조회조건에 추가했습니다
- 커피챗 엔터티
- soft delete위해 @SQLDelete 어노테이션 추가
- isDeleted 필드 디폴트 값 명시
- Controller, Service 클래스 수정
- 커피챗 레포지토리에서 단건 조회시 삭제여부 조건을 포함한 메서드를 추가
- 서비스 계층의 단건 조회 공통메서드에서 추가한 해당 메서드를 사용하도록 변경
- closes: #110 
---
어떤 변경 사항이 있나요?
=>  Feature: 커피챗 삭제 API 구현

module-api/src/main/java/kernel/jdon/skill/controller/SkillController.java, module-api/src/main/java/kernel/jdon/skill/dto/response/FindHotSkillResponse.java, module-api/src/main/java/kernel/jdon/skill/dto/response/FindListHotSkillResponse.java, module-api/src/main/java/kernel/jdon/skill/service/SkillService.java, module-domain/src/main/java/kernel/jdon/skill/repository/SkillRepository.java, module-domain/src/main/java/kernel/jdon/skill/repository/SkillRepositoryCustom.java, module-domain/src/main/java/kernel/jdon/skill/repository/SkillRepositoryImpl.java
- Feature: 요즘 뜨는 기술 스택 조회 API 구현
-  요즘 뜨는 기술 스택 조회 API 구현하였습니다.
- querydsl 사용으로 인해 custom repository를 interface로 생성하고 인터페이스를 구현한 impl 클래스를 생성하였습니다.
- skill 테이블에서 가장 많이 추출된 키워드 10개를 조회하도록 sql을 작성했습니다.
- 로컬 환경에서 api를 호출한 결과를 확인했습니다.
- closes: #121 
---
어떤 변경 사항이 있나요?
=> Feature: 요즘 뜨는 기술 스택 조회 API 구현

module-crawler/src/main/java/kernel/jdon/crawler/wanted/converter/EntityConverter.java, module-crawler/src/main/java/kernel/jdon/crawler/wanted/dto/object/CreateSkillDto.java, module-crawler/src/main/java/kernel/jdon/crawler/wanted/service/WantedCrawlerService.java, module-crawler/src/main/java/kernel/jdon/crawler/wanted/skill/BackendSkillType.java, module-crawler/src/main/java/kernel/jdon/crawler/wanted/skill/FrontendSkillType.java, module-crawler/src/main/java/kernel/jdon/crawler/wanted/skill/SkillType.java, module-domain/src/main/java/kernel/jdon/skill/repository/SkillRepository.java, module-domain/src/main/java/kernel/jdon/skill/repository/SkillRepositoryCustom.java, module-domain/src/main/java/kernel/jdon/skillhistory/domain/SkillHistory.java, module-domain/src/main/java/kernel/jdon/skillhistory/repository/SkillHistoryRepository.java
- 원티드 스크래핑 skill 데이터 적재 방식 변경
- 원티드 스크래핑 skill 데이터 히스토리 테이블 추가
- Skill 테이블에 우리 서비스에서 사용할 기술스택을 미리 정의하여 데이터베이스와 Enum타입으로 서버에 저장해두고, 그 이외의 키워드로 들어오는 기술스택은 '기타'로  데이터가 삽입되도록 수정하였습니다.
- 사전에 정의한 기술스택을  Enum타입으로 서버에 저장해두었기 때문에 데이터베이스에서 데이터의 유무를 결정하는 것이 아니라 **서버 내에서 즉시 확인**할 수 있으며 이로인해서 **데이터베이스에 질의를 통해 존재하는 기술스택인지 확인하지 않아도 되도록 문제를 해결**하였습니다.
또한 **다대다 관계에서 중간테이블을 저장하기 위해 해당 JD에 포함된 스킬목록을 메모리에 저장하지 않아도** 되기 때문에 서버 부하를 줄일 수 있습니다. 
이로인해 기술스택의 존재 유무를 서버에서 비교함에 따라 데이터베이스에 있는 기술스택과 Enum 타입의 기술스택을 의미하는 각각의 필드들이 동기화가 되어야 하는 제약조건이 있습니다.
하지만 서버에 부하가되는 단점보다 장점이 더 많은 상황이라서 해당 방법을 채택하였고 적용하였습니다.
사전에 정의한 기술스택과 기술스택을 결정한 배경은 아래의 노션페이지에서 확인할 수 있습니다.
https://www.notion.so/678ab1bfd8a64c51a2b2715d627785f6?pvs=4
- 추출된 기술스택을 중복제거 없이 모두 skill_history 테이블에 추가하여 이력을 관리하며 이 테이블을 통해 추출된 기술스택의 count를 알 수 있도록 설계하였습니다. …
=> Refactor: 원티드 JD의  skill 데이터 적재 방식 변경

module-api/src/main/java/kernel/jdon/member/controller/MemberController.java, module-api/src/main/java/kernel/jdon/member/service/MemberService.java, module-common/src/main/java/kernel/jdon/error/code/api/MemberErrorCode.java, module-domain/src/main/java/kernel/jdon/member/repository/MemberRepository.java
- `POST` `/api/v1/nickname/duplicate` 구현
- 닉네임이 중복된 닉네임인지 확인하는 API 구현했습니다. 
- 본인 닉네임과 같은 닉네임이면 이미 해당 닉네임이라는 에러를, 다른 유저가 사용중인 닉네임이면 이미 존재하는 닉네임이라는 에러를 반환합니다. 
- closes: #142 
---
어떤 변경 사항이 있나요?
=> Feature: 닉네임 중복 확인하는 API 구현

module-api/build.gradle, module-api/src/main/java/kernel/jdon/coffeechat/dto/request/CreateCoffeeChatRequest.java, module-api/src/main/java/kernel/jdon/coffeechat/dto/request/UpdateCoffeeChatRequest.java, module-api/src/main/java/kernel/jdon/coffeechat/dto/response/FindCoffeeChatResponse.java, module-api/src/test/java/kernel/jdon/coffeechat/controller/CoffeeChatControllerTest.java
- 커피챗 단건 CRUD에 대한 컨트롤러 계층 테스트를 작성했습니다
- 시큐리티 적용에 따른 test 의존성 추가
- 응답 및 요청 dto에 빌더 추가
- 각 crud 메서드별로 mock Service 객체와 mockMvc 활용하여 성공 로직 작성
- closes: #122 
---
어떤 변경 사항이 있나요?
=> Test: 커피챗 컨트롤러 단위테스트 작성

module-domain/build.gradle
- `ModuleApiApplication`이나 `ModuleCrawlerApplication`을 실행할 때, `module-domain`의 main/generated 아래에 Q 클래스가 생성되는 문제
- 참고로, `module-domain` 자체를 build할 때는 src 파일과 같은 레벨에 build파일이 정상적으로 생성되었음
- `build` 디렉토리 내에 Q 클래스 파일들이 생성되도록 querydsl 설정을 변경
- `build` 디렉토리
```java
def buildDir = 'build'
```
- 소스코드가 있는 곳으로 **인식**하는 부분입니다.
```java
sourceSets {
main.java.srcDir buildDir
}
```
- `JavaCompile` 시, 생성된 소스 코드의 **출력 경로**로 변경했습니다.
Querydsl **어노테이션 프로세서**가 이 경로에서 Q 클래스 파일을 생성하도록 합니다. 
```java
tasks.withType(JavaCompile) {
options.annotationProcessorPath = configurations.annotationProcessor
options.compilerArgs += ['-s', buildDir]
}
```
- `clean`할 때 **삭제할 디렉토리**도 동일하게 설정했습니다.
```java
def buildDir = 'build'
clean {
delete file(buildDir)
}
```
- closes: #148 
---
어떤 변경 사항이 있나요?
=> Fix: Q 클래스가 생성되는 문제 해결

module-api/src/main/java/kernel/jdon/config/OAuth2SecurityConfig.java
로그아웃을 위한 api 구현했습니다. 
- security chain에서 `api/v1/logout`으로 요청을 보내면 해당 유저의 세션을 삭제하고, JSESSIONID 쿠키도 삭제한 후 프론트의 메인 페이지로 리다이렉트하는 코드를 추가했습니다. 
- oauth2Login() 에서 deprecate된 userInfoEndpoint() 메서드를 쓰고 있어서 현재 버전에서 지원하고 있는 userInfoEndpoint() 메서드 시그니처 형식으로 변경했습니다. 
- 아마 람다 형식으로 쓰기를 권장하는 것 같습니다. 
`/api/v1/logout`으로 요청을 보내면 쿠키와 세션이 삭제되고, 설정한 리다이렉트 url로 이동합니다. 
- closes: #153
- 프론트 분들과 상의하여 리다이렉트할 프론트 페이지의 endpoint를 수정해야합니다.  
---
어떤 변경 사항이 있나요?
=> Feature: 로그아웃 API 구현하기

module-api/build.gradle, module-api/src/main/java/kernel/jdon/skill/dto/object/FindHotSkillDto.java, module-api/src/main/java/kernel/jdon/skill/dto/response/FindListHotSkillResponse.java, module-api/src/main/java/kernel/jdon/skill/repository/SkillRepositoryCustom.java, module-api/src/main/java/kernel/jdon/skill/repository/SkillRepositoryImpl.java, module-api/src/main/java/kernel/jdon/skill/service/SkillService.java, module-crawler/src/main/java/kernel/jdon/crawler/wanted/service/WantedCrawlerService.java, module-domain/build.gradle
- skill 데이터 적재 방식 변경에 따른 기술스택 조회 API의 SQL 수정
- skill_history 테이블을 기준으로 가장 많이 추출된 기술스택을 반환하도록 수정하였습니다.
API 명세에 맞게 데이터를 반환합니다.
- closes: #159 
---
어떤 변경 사항이 있나요?
=> Fix: 요즘 뜨는 기술스택 조회 API 수정

module-api/src/main/java/kernel/jdon/config/OAuth2SecurityConfig.java, module-api/src/main/java/kernel/jdon/skill/controller/SkillController.java, module-api/src/main/java/kernel/jdon/skill/dto/response/FindJobCategorySkillResponse.java, module-api/src/main/java/kernel/jdon/skill/repository/SkillRepository.java, module-api/src/main/java/kernel/jdon/skill/service/SkillService.java
- API 구현 : [직군 별 기술 스택 조회하기](https://www.notion.so/d7734d2eeb364296b7aaf66a1b06bb3e?pvs=4)
- api 명세서 기반으로 직군 별 기술 스택 조회하기 API 구현
- closes: #138 
---
어떤 변경 사항이 있나요?
=> Feature: 직군 별 기술 스택 조회하기 API 구현

module-api/src/main/java/kernel/jdon/config/OAuth2SecurityConfig.java
security filter에서 corsFilter를 커스텀했습니다. 
이제 `localhost:3000` 에서 오는 요청은 허용됩니다. 
다음과 같이 설정하지 않은 도메인에서 온 요청은 cors 에러가 나고 
설정한 도메인에서 온 요청은 cors 에러가 나지 않습니다. 
- closes: #164 
---
어떤 변경 사항이 있나요?
=> Feature: Add corsFilter setting

module-api/src/main/java/kernel/jdon/faq/dto/request/CreateFaqRequest.java, module-api/src/main/java/kernel/jdon/faq/service/FaqService.java
- faq create request에서 불필요하게 static method로 처리한 toEntity()를 인스턴스 메서드로 변경했습니다. 
- request dto에 대해서 생성자를 쓸일이 없어 default 생성자와 private 옵션 추가했습니다. 
응답 결과가 달라진 것은 없습니다. 
- closes: #174
---
어떤 변경 사항이 있나요?
=> Refactor: 불필요한 static method 수정

module-api/src/main/java/kernel/jdon/coffeechat/service/CoffeeChatService.java, module-api/src/main/java/kernel/jdon/global/page/CustomPageResponse.java
응답DTO는 정적 팩토리 메서드를 사용하는 컨벤션에 따라
CustomPageResponse에 정적 팩토리 메서드를 추가했습니다.
- CustomPageResponse
- @AllArgsConstructor 어노테이션 추가
- 정적 팩토리 메서드 of 작성
- 그에 따라 Page관련 정보를 묶기위해 선언한 이너 클래스도 static으로 변경
- 생성자로 CustomPageResponse를 사용하던 CoffeeChatService를 정적 팩토리 메서드를 사용하도록 변경
- closes: #192
---
어떤 변경 사항이 있나요?
=> Refactor : CustomPageResponse 정적 팩토리 메서드 추가

module-api/src/main/java/kernel/jdon/favorite/service/FavoriteService.java
- 영상 찜하기 API 이미 찜한 강의 새로 생성되는 문제 해결하였습니다.
- favorite을 생성할 때, 해당 찜이 존재하는지 확인 후, 존재하지 않을 때만 새로 생성하도록 변경하였습니다.
- closes: #183 
---
어떤 변경 사항이 있나요?
=> Bugfix: 영상 찜하기 API 이미 찜한 강의 새로 생성되는 문제 해결 

module-api/src/main/java/kernel/jdon/config/auth/OAuth2SecurityConfig.java
프론트 배포 주소를 cors allow origin 주소에 허용했습니다.
- closes: #
---
어떤 변경 사항이 있나요?
=> Fix: cors 허용 origin에  프론트 배포 주소 추가

module-domain/src/main/java/kernel/jdon/skillhistory/domain/SkillHistory.java
- skill_history 테이블 유니크 인덱스 키 삭제
- skillHistory 엔티티 @Table uniqueConstraints 속성 제거
- skillHistory 엔티티 @Table uniqueConstraints 속성을 제거하였습니다.
- skill_history 테이블 유니크 인덱스 키 삭제하였습니다.
- ✅ application.yml파일에 ddl_auto 속성이 update로 되어있다고 하더라도 유니크키가 지워지지 않습니다. 따라서 직접 DB에서 삭제가 필요합니다. 로컬환경에서 ddl_auto를 create로 변경해 데이터베이스를 초기화하는 방법으로 적용하시거나, 로컬 DB에서도 아래 예시와 같이 삭제하시기 바랍니다.(로컬 DB에 저장된 FK, UK는 직접 확인하셔서 적용해야합니다.)
- skill_history 테이블 유니크 인덱스 키가 외래키 제약조건이 걸려있어 바로 삭제가 불가해서 외래키 제약조건 제거 -> 인덱스 키 제거 -> 삭제한 외래키 제약조건 재등록 합니다.
```
ALTER TABLE skill_history DROP FOREIGN KEY FKmrhqafug43nxomrtg31jqilli;
ALTER TABLE skill_history DROP FOREIGN KEY FKagj3pewuv9e0s3t9yskagvyoq;
ALTER TABLE skill_history DROP INDEX UKt9ommi1gl0f5wbbuvr9t5yhst;
ALTER TABLE skill_history ADD CONSTRAINT FKagj3pewuv9e0s3t9yskagvyoq FOREIGN …
```
=> Bug: skill_history 테이블 유니크 인덱스 키 삭제 

module-api/src/main/java/kernel/jdon/coffeechat/controller/CoffeeChatController.java, module-api/src/main/java/kernel/jdon/coffeechat/error/CoffeeChatErrorCode.java, module-api/src/main/java/kernel/jdon/coffeechat/repository/CoffeeChatRepository.java, module-api/src/main/java/kernel/jdon/coffeechat/service/CoffeeChatService.java, module-domain/src/main/java/kernel/jdon/coffeechat/domain/CoffeeChat.java, module-domain/src/main/java/kernel/jdon/coffeechatmember/domain/CoffeeChatMember.java
커피챗 신청 API를 구현했습니다
- 커피챗 엔터티가 신청로직에 대한 책임을 지도록 했습니다
- CoffeeChatMember 레포지토리를 두지않고 CoffeeChat에서만 신청여부를 관리합니다
- CoffeeChatRepository
-  신청가능한 커피챗을 찾아오도록 쿼리메소드를 추가했습니다
- CoffeeChatErrorCode
- 예외 상황에 따른 에러코드를 추가했습니다 
- CoffeeChatService
- apply 메서드에서 db에서 신청하고자 하는 엔터티를 찾아올 때 상태 칼럼이 OPEN인지 확인하고 결과가 없으면 예외를 던지도록 했습니다. 
- 커피챗 상태와 삭제여부 상태를 구분하기 위해 findById 공통 메서드를 'findExist~'로 변경했습니다.
- 커피챗을 개설한 host가 guest로서 참여신청을 하는 경우 예외를 던집니다.
- CoffeeChatEntity
- coffeeChat 엔터티가 신청에 대한 책임을 갖도록 했습니다.
- coffeeChatMemberList에 cascade.ALL, orphanRemoval 옵션을  적용해서
coffeeChat만 변경되어도 coffeeChatMember에도 변경사항이 반영되도록 했습니다. 
- updateStatusByRecruitCount 메소드를 재활용해서 참여인원에 따라 상태를 변경합니다.
- CoffeeChatMember
- 연결 엔터티 생성을 위해 정적 팩토리 메서드를 추가 했습니다
- 아래와 같이 status가 open인 커피챗에 참여신청을 하면
- currentRecruitCount가 올라가고 …
=> Feature: 커피챗 신청 API

module-api/src/main/java/kernel/jdon/coffeechat/dto/response/FindCoffeeChatListResponse.java, module-api/src/main/java/kernel/jdon/coffeechat/dto/response/FindCoffeeChatResponse.java
커피챗 상세,목록조회 응답 Dto에 누락된 항목이 있어 추가했습니다.
- FindCoffeeChatListResponse
- 개설자 JobCategory와 createdDate를 포함하도록 수정
- FindCoffeeChatResponse
- 개설자 JobCategory를 포함하도록 수정
- closes: #217 
---
어떤 변경 사항이 있나요?
=> Fix: 커피챗 상세와 목록조회에서 누락된 항목을 포함하도록 수정

module-api/src/main/java/kernel/jdon/skill/controller/SkillController.java, module-api/src/main/java/kernel/jdon/skill/dto/object/FindLectureDto.java, module-api/src/main/java/kernel/jdon/skill/repository/SkillRepositoryCustom.java, module-api/src/main/java/kernel/jdon/skill/repository/SkillRepositoryImpl.java, module-api/src/main/java/kernel/jdon/skill/service/SkillService.java
- 기술 스택 기반 원티드JD, 인프런 강의 데이터 조회 API의 인프런 강의데이터에 회원 별 찜 유무 항목을 반환하도록 수정했습니다.
- 동적쿼리로 구현하였습니다.
- 로그인하지 않은 경우 SessionUserInfo가 null -> userId가 null일 때 SkillRepositoryImpl에서 isFavorite를 false로 반환하도록 구현했습니다.
- 로그인 한 경우 SkillRepositoryImpl의 isFavoriteLectureByMember 메서드를 통해서 매개변수 userId로 favorite 테이블의 매핑되는 강의 데이터가 존재한다면 true를 반환하도록 구현했습니다.
- 로그인하지 않았다면 isFavorite 항목이 false로 반환됩니다.
- 로그인 상태일 때 찜 한 강의는 true로 반환됩니다. 
- closes: #199  #189 
---
어떤 변경 사항이 있나요?
=> Fix: 메인화면 강의데이터에 회원 별 찜 유무 항목 추가

module-api/src/main/java/kernel/jdon/coffeechat/controller/CoffeeChatController.java, module-api/src/main/java/kernel/jdon/config/auth/OAuth2SecurityConfig.java, module-api/src/main/java/kernel/jdon/member/controller/MemberController.java, module-api/src/main/java/kernel/jdon/skill/controller/SkillController.java
- favorite 도메인을 제외한 다른 api를 원래대로 sessionUserInfo를 사용하도록 되돌렸습니다. 
- closes: #
---
어떤 변경 사항이 있나요?
=> Fix: userId 고정시켰던 api 일부 되돌림

module-api/src/main/java/kernel/jdon/coffeechat/controller/CoffeeChatController.java, module-api/src/main/java/kernel/jdon/coffeechat/dto/response/FindCoffeeChatResponse.java, module-api/src/main/java/kernel/jdon/coffeechat/repository/CoffeeChatRepository.java, module-api/src/main/java/kernel/jdon/coffeechat/service/CoffeeChatService.java, module-api/src/main/java/kernel/jdon/coffeechatmember/repsitory/CoffeeChatMemberRepository.java
로그인한 유저가 신청한 커피챗 목록을 조회하는 API를 구현했습니다.
CoffeeChatMember 연결엔터티 Repositroy를 통해 조회하며
N+1 해결을 위해 페치조인을 통해 한번의 쿼리로 조회하도록 했습니다.
- CoffeeChatMemberRepository
- CoffeeChatMemberdomainRepository를 상속 받도록 수정했습니다
- N+1 해결을 위해 페치조인을 통해 한번의 쿼리로 조회하도록 했습니다.
- 그 외 사용하지 않는 쿼리메소드나 불필요한 파싱등을 제외했습니다
lazy로딩하던 엔터티들을 페치조인을 통해 한번에 조회합니다.
- closes: #202 
---
어떤 변경 사항이 있나요?
=> Feature: 내가 신청한 커피챗 목록 조회 API

module-crawler/src/main/java/kernel/jdon/crawler/config/ScrapingInflearnConfig.java, module-crawler/src/main/java/kernel/jdon/crawler/inflearn/service/InflearnCrawlerService.java, module-crawler/src/main/java/kernel/jdon/crawler/inflearn/service/infrastructure/DynamicSleepTimeManager.java, module-crawler/src/main/resources/application.yml
- 크롤링 요청 보낼 때의 대기 시간을 동적으로 조정했습니다.
- 연속적으로 성공적인 요청 후 대기 시간을 줄이고, 실패한 요청이 있으면 대기 시간을 늘리는 방식을 사용했습니다.   
- `INITIAL_SLEEP_TIME`을 무작위로 생성함으로써 클롤러 요청의 패턴을 불규칙하게 만들어 크롤러 탐지를 어렵게 바꿨습니다.
- `Thread.sleep(2000)` -> `Thread.sleep(dynamicSleepTime)`으로 변경하였습니다.
- 클로링해온 결과는 같습니다.
- closes: # 206
---
어떤 변경 사항이 있나요?
=> Refactor: 인프런 크롤링에서 동적으로 크롤링 시간 조정

module-api/src/main/java/kernel/jdon/coffeechat/controller/CoffeeChatController.java, module-api/src/main/java/kernel/jdon/coffeechat/error/CoffeeChatErrorCode.java, module-api/src/main/java/kernel/jdon/coffeechat/service/CoffeeChatService.java, module-api/src/main/java/kernel/jdon/coffeechatmember/repsitory/CoffeeChatMemberRepository.java
커피챗 신청시 이미 참여한 사람이 신청하는 경우 예외처리
처음엔 메모리에서 객체그래프 탐색을 통해 coffeeChat이 갖고 있는 참여자 목록에 신청자 엔터티가 존재하는지 확인하려고 했으나
커피챗 참여자가 많을수록 모두 메모리에 올려야 하므로 메모리 사용량이 증가할 수 있습니다.
exist 질의를 통해 메모리 사용량을 최소화 하면서 필요한 정보만 확인하도록 했습니다.
- CoffeeChatMemberRepository
- 기존 참여여부 질의를 위해 쿼리메소드 추가
- CoffeeChatService
- apply 메서드에서 검증로직이 늘어남에 따라 validateApplyRequest 하나의 메서드로 통합했습니다
- 이미 참여한 커피챗일 경우 예외를 반환합니다
이미 참여한 커피챗에 참여신청시 예외가 발생합니다
- closes: #234 
---
어떤 변경 사항이 있나요?
=> BugFix: 커피챗 중복 참여신청 시 예외처리

module-crawler/src/main/java/kernel/jdon/crawler/config/ScrapingInflearnConfig.java, module-crawler/src/main/java/kernel/jdon/crawler/inflearn/service/CourseParserService.java, module-crawler/src/main/java/kernel/jdon/crawler/inflearn/service/InflearnCrawlerService.java, module-crawler/src/main/resources/application.yml
- 인프런 강의 url이 목록 페이지로 들어가고 있어서 상세페이지 url이 제대로 들어가도록 수정했습니다.
- closes: #240 
---
어떤 변경 사항이 있나요?
=> Fix: 인프런 강의 url 상세페이지가 담기도록 수정

module-api/src/main/java/kernel/jdon/coffeechat/controller/CoffeeChatController.java, module-api/src/main/java/kernel/jdon/coffeechat/dto/request/CoffeeChatCondition.java, module-api/src/main/java/kernel/jdon/coffeechat/dto/request/CoffeeChatSortCondition.java, module-api/src/main/java/kernel/jdon/coffeechat/dto/response/FindCoffeeChatListResponse.java, module-api/src/main/java/kernel/jdon/coffeechat/repository/CoffeeChatRepository.java, module-api/src/main/java/kernel/jdon/coffeechat/repository/CoffeeChatRepositoryImpl.java, module-api/src/main/java/kernel/jdon/coffeechat/repository/CustomCoffeeChatRepository.java, module-api/src/main/java/kernel/jdon/coffeechat/service/CoffeeChatService.java, module-api/src/main/java/kernel/jdon/config/WebConfig.java
- [커피챗 목록 조회하기](https://www.notion.so/7c7962a4b1104cc5a6a79d172596863c?pvs=4) API 구현
- 입력되는 커피챗 제목, 정렬 조건, 직군 조건에 따라 동적으로 SQL을 변경하도록 querydsl을 사용하여 동적쿼리를 구현하였습니다.
- 내가 신청, 참여한 커피챗조회에서 사용하는 `FindCoffeeChatListResponse`를 재사용하기위해 커피챗 목록조회 API에 없는 항목인 isDeleted를 반환하지 않도록 `@JsonInclude(JsonInclude.Include.NON_NULL)`어노테이션을 추가하고 필드 타입을 null을 담을 수 있는 Boolean 레퍼런스 타입으로 수정했습니다.
-  커피챗 목록조회 API에서 반환하는 필드를 인자로 받는 생성자를 추가하고 `@QueryProjection` 어노테이션을 통해 DTO를 Q타입으로 생성하였습니다.
- findCoffeeChatList 메서드에서 메인쿼리에서 커피챗 등록자의 닉네임을 가져오기 위해 coffeechat과 member, 커피챗 등록자의 직군명을 가져오기위해 member와 jobcategory를 조인합니다. 
- Count쿼리에서는 커피챗 등록자의 직군명을 가져올 필요가 없기 때문에 member와 jobcategory와 조인없이 coffeechat과 member만을 조인하도록 하여 최종적으로 조인연산을 줄이도록 했습니다.
- 정적인 정렬조건 데이터를 서버에서 일관성있게 관리할 수 있도록 CoffeeChatSortCondition enum 클래스를 생성했습니다.
- …
=> Feature: 커피챗 목록조회 API 구현

module-api/src/main/java/kernel/jdon/auth/service/JdonOAuth2UserService.java, module-api/src/main/java/kernel/jdon/config/auth/JdonOAuth2AuthenticationSuccessHandler.java, module-api/src/main/resources/application-dev.yml, module-api/src/main/resources/application-local.yml, module-api/src/main/resources/application-prod.yml, module-domain/src/main/java/kernel/jdon/member/domain/Member.java
- application.yml에 logout 성공 시 redirect 주소 변경했습니다.  이 버전으로 업데이트하면 로그아웃 했을 때 메인 페이지로 넘어갑니다. 
- 로그인했을 때 마지막 로그인 일시를 업데이트하지 않았는데, 이제 업데이트하도록 추가했습니다. 
- lastLoginDate
- 추가 설명 
DB에 따로 timezone 설정을 하지 않아 UTC(한국시간 - 9시간) 기준으로 저장되지만 서버에서 값을 가져올 때는 아래사진과 같이 알아서 시간차를 설정하므로 크게 상관은 없습니다. 
- closes: #248 
---
어떤 변경 사항이 있나요?
=> Fix: 마지막 마지막 로그인 datetime DB에 업데이트 하도록 수정

module-api/src/main/java/kernel/jdon/config/auth/OAuth2SecurityConfig.java
securityConfig에 API 별로 권한 설정
이제 login 하지 않은 유저가 보내면 안될 요청을 보내면 sessionUserInfo null 로 인한 500 에러가 아니라 401 혹은 403 에러로 반환됩니다. 
지옥의 test 완료했습니다
- closes: #259 
---
어떤 변경 사항이 있나요?
=> Fix: login 없이 test를 위해서 풀어놨던 api별 권한 재설정

module-api/src/main/java/kernel/jdon/coffeechat/dto/response/FindCoffeeChatResponse.java
커피챗 상세 조회 시 로그인한 유저가 개설자인지 여부에 따라 UI를 다르게 그려야 하므로
명확하게 구분하기 위해서 응답 Dto에 개설자의 Id도 포함하도록 했습니다
- closes: #223 
---
어떤 변경 사항이 있나요?
=> BugFix: 커피챗 상세조회 시 응답DTO에 커피챗 개설자 식별자를 포함

module-api/src/main/java/kernel/jdon/faq/error/FaqErrorCode.java, module-api/src/main/java/kernel/jdon/faq/service/FaqService.java, module-api/src/main/java/kernel/jdon/global/exception/BaseThrowException.java, module-api/src/test/java/kernel/jdon/faq/service/FaqServiceTest.java
- 스프링 멘토님이 추천해주신 예외 발생 방식을 가장 간단한 FAQ 도메인에 시범 적용했습니다.
- 권태관 멘토님이 추천하신 테스트코드의 DisplayName을 수정했습니다.
다음과 같은 이유로 위 사항을 수정했습니다.
기존 예외 발생 소스와 같이 관리된다면 log를 작성해야하는 요구사항이 있을경우
두가지 방안이 있을 것 같습니다.
1. ExceptionHandler 같은 부분에서 ApiException이 발생한 부분을 캐치하는 메서드에서 CofeeChatErrorCode를 인자로 갖는 부분을 분기처리해서  log를 달도록 구현한다.
= 요구사항을 처리할 수는 있지만 CofeeChatErrorCode가 **호출되는 시점에 log를 작성하지 못해서** ExceptionHandler가 수정되어야하며 CofeeChatErrorCode에서 처리해야할 일을 ExceptionHandler이 처리해야합니다. 또한 다른 도메인 예외마다 요구사항이 추가된다면 ExceptionHandler의 ApiException이 발생한 부분을 캐치하는 메서드에 도메인 ErrorCode 별로 분기 처리하는 등 계속 ExceptionHandler가 수정되어야 합니다. 이로인해 ExceptionHandler가 추가 요구사항이 있는 모든 도메인의 ErrorCode에 의존하게 됩니다.
결론적으로 매우 비효율적입니다.
2. ApiException 생성자에서 매개변수로 받는 추상화된 ErrorCode가 어떤 것으로 들어오는지 확인하여 로그를 추가한다.
= ApiException이 생성될 때 도메인 별로 로그를 추가할 수 있으나 이 방법도 1번 방안과 …
=> Refactor: FaqErrorCode 리팩토링 

module-api/build.gradle, module-api/src/main/java/kernel/jdon/coffeechat/controller/CoffeeChatController.java, module-api/src/main/java/kernel/jdon/coffeechat/error/CoffeeChatErrorCode.java, module-api/src/main/java/kernel/jdon/coffeechat/service/CoffeeChatApplyFacade.java, module-api/src/main/java/kernel/jdon/config/redis/CoffeeChatLockConfig.java, module-api/src/main/java/kernel/jdon/global/exception/ApiException.java, module-api/src/main/resources/application-dev.yml, module-api/src/main/resources/application-local.yml, module-api/src/main/resources/application-prod.yml, module-api/src/test/java/kernel/jdon/moduleapi/coffeechat/controller/CoffeeChatControllerTest.java, module-api/src/test/java/kernel/jdon/moduleapi/coffeechat/service/CoffeeChatServiceTest.java, module-api/src/test/resources/application.yml, module-domain/src/main/java/kernel/jdon/coffeechat/domain/CoffeeChat.java
- 총 모집인원이 한정되어 있는 커피챗에 동시에 여러 인원이 참여신청하는 경우 동시성 이슈가 발생할 수 있습니다.
- 이를 레디스를 활용해서 해결했습니다.
- 배경
- 프로젝트 최초 기획부터 다중서버 분산환경으로 확장을 고려
- 세션방식 로그인을 채택했고, 분산환경을 고려했기에 세션 클러스터링을 위해 Redis를 도입했음
- 고려한 선택지
-  Synchronized 키워드
- Synchronized는 하나의 JVM 내에서만 동기화를 보장합니다. 따라서 여러 서버에 분산된 애플리케이션에서는 synchronized 키워드만으로는 동시성 제어를 할 수 없습니다. 그래서 실무에서도 잘 쓰지 않습니다.
-  MySQL의 네임드락 기능
- 락을 획득하는 과정에서 커넥션풀을 사용해야 합니다. 기존 비즈니스 로직 상에서 쓰는 커넥션풀을 같이 쓰면 기존 로직에 영향이 갈 수 있기에 별도 커넥션풀을 관리해야 한다는 단점으로 제외했습니다.
-  Redis
- 메모리 기반으로 db보다 빠르게 락을 획득하고 반납할 수 있다
- 별도의 커넥션풀을 관리하지 않아도 된다
- 분산락을 위한 편리한 인터페이스를 지원한다
- Lettuce VS Redisson 
- 자바에서 redis를 쓰기위해 주요 사용되는 여러 라이브러리들이 있는데 그중 대표적인 2가지가 Lettuce와 Redisson입니다.
그중 아래 특성을 고려해서 Redisson 을 채택했습니다.
- Lettuce는 공식적으로 분산락을 위한 기능을 제공하지는 않고 직접 구현해서 사용해야 합니다. 락을 획득에 실패하면 지속적으로 획득 요청을 보내는 스핀락 형태로 구성하게 됩니다. …
=> Feature: 커피챗 동시성 제어

module-api/src/main/java/kernel/jdon/coffeechat/repository/CoffeeChatRepositoryImpl.java
- 커피챗 목록 조회에서 삭제된 커피챗 조회되는 현상 수정
- 커피챗 목록 조회 SQL 조건절에 `is_deleted = false` 조건을 추가하였습니다.
- excludeDeleteCoffeeChat() 메서드 추가
API 요청 시 삭제된 커피챗이 조회되지 않는 것을 확인했습니다.
- closes: #282 
---
어떤 변경 사항이 있나요?
=> Bug: 커피챗 목록 조회에서 삭제된 커피챗 조회되는 현상 수정

module-crawler/src/main/java/kernel/jdon/crawler/config/ScrapingWantedProperties.java, module-crawler/src/main/java/kernel/jdon/crawler/wanted/search/JobSearchJobPosition.java, module-crawler/src/main/java/kernel/jdon/crawler/wanted/service/WantedCrawlerService.java, module-crawler/src/main/java/kernel/jdon/crawler/wanted/service/infrastructure/JobDetailProcessingCounter.java, module-crawler/src/main/java/kernel/jdon/crawler/wanted/service/infrastructure/JobListProcessingCounter.java
- 멘토링때 조언받은 부분에 대한 리팩토링을 적용했습니다.
- application.yml의 프로퍼티 값을 바인딩하는 객체의 클래스명을 좀 더 명확한 의미인 ScrapingWantedConfig -> ScrapingWantedProperties 로 변경하였습니다.
- ScrapingWantedProperties 객체 내부의 값을 사용하는 쪽에서 체이닝해서 가져오는 것이 아니라 ScrapingWantedProperties가 바로 반환할 수 있도록 getter 메서드를 추가하고 사용하는 쪽에서 해당 메서드로 객체에 접근하도록 수정하였습니다.
- JobSearchJobPosition 생성자에 List<SkillType>를 추가하여 직군별 직무 객체인 JobSearchJobPosition가 해당 스킬목록을 가지고 있도록 수정하였습니다.
따라서 WantedCrawlerService.createWantedJdSkill() 에서
```
SkillType[] skillTypes = (jobPosition == JobSearchJobPosition.JOB_POSITION_SERVER)
? BackendSkillType.values()
: FrontendSkillType.values();
```
위와 같이 상태에 따라 SkillType을 초기화하지 않도록 수정하였습니다.
- WantedCrawlerService.createWantedJdSkill() 에서 추출한 기술스택이 SkillType(열거형 클래스)에 포함되어있는지 루프를 돌아 체크하고, 사용하는 쪽에서 또 루프를 돌아서 해당 keyword에 접근하던 로직을
``` …
```
=> Refactor: 원티드 스크래핑 비즈니스로직 리팩토링

module-api/src/main/java/kernel/jdon/auth/controller/AuthController.java, module-api/src/main/java/kernel/jdon/auth/service/JdonOAuth2UserService.java, module-api/src/main/java/kernel/jdon/config/auth/JdonAuthExceptionHandler.java, module-api/src/main/java/kernel/jdon/config/auth/OAuth2SecurityConfig.java, module-api/src/main/java/kernel/jdon/global/exception/AuthException.java, module-api/src/main/java/kernel/jdon/global/exception/GlobalExceptionHandler.java
- 프론트에서 페이지를 그리기 위해 유저의 로그인 유무를 확인해야하는데 이때 사용할 API를 작성했습니다. 
인증받은 유저라면 해당 API를 요청했을 때 204가, 인증받은 유저가 아니라면 401 에러가 반환됩니다. 
- auth 로직 중 error가 발생하면 writer를 통해서 error를 리턴하고 있었는데, GlobalExceptionHandler(@RestControllerAdvice) 에서 AuthException을 잡아서 핸들링하도록 수정했습니다.
- 프론트 요청으로 cors 허용 origin  하나 더 추가했습니다. 
- Auth 관련 Exception 클래스의 이름을 좀 더 포괄적으로 `UnAuthorizationException`에서 `AuthException`으로 변경했습니다. 
- closes: #257 
- closes: #271 
---
어떤 변경 사항이 있나요?
=> Feature: 유저의 로그인 상태를 확인할 수 있는 API 구현

module-api/src/main/java/kernel/jdon/auth/service/AuthService.java, module-api/src/main/java/kernel/jdon/auth/service/JdonOAuth2UserService.java, module-api/src/main/java/kernel/jdon/auth/service/LoginUserArgumentResolver.java, module-api/src/main/java/kernel/jdon/coffeechat/controller/CoffeeChatController.java, module-api/src/main/java/kernel/jdon/config/auth/JdonAuthExceptionHandler.java, module-api/src/main/java/kernel/jdon/config/auth/JdonLogoutSuccessHandler.java, module-api/src/main/java/kernel/jdon/config/auth/JdonOAuth2AuthenticationSuccessHandler.java, module-api/src/main/java/kernel/jdon/config/auth/LoginRedirectUrlConfig.java, module-api/src/main/java/kernel/jdon/config/auth/LoginRedirectUrlProperties.java, module-api/src/main/java/kernel/jdon/config/auth/LogoutRedirectUrlProperties.java, module-api/src/main/java/kernel/jdon/config/auth/OAuth2SecurityConfig.java, module-api/src/main/java/kernel/jdon/config/auth/WithdrawProperties.java, module-api/src/main/java/kernel/jdon/global/exception/GlobalExceptionHandler.java, module-api/src/main/resources/application-dev.yml, module-api/src/main/resources/application-local.yml, module-api/src/main/resources/application-prod.yml, module-domain/src/main/java/kernel/jdon/member/domain/MemberRole.java
프론트 개발 환경이 jdon.kr이냐 localhost:3000이냐에 따라 확인하기 위한 redirect 주소를 jdon.kr, 혹은 localhost:3000으로 보내기 위해서 해당되는 yml파일로 계속해서 재 실행시켜야하는 문제가 있었습니다. 따라서 들어온 요청의 referer를 확인하여 이 요청이 localhost:3000으로부터 온 요청이라면 redirect를 localhost:3000으로  아니라면 그 호스트로 던져주도록 수정했습니다. 
따라서 application-dev.yml에 localhost:3000이 host인 곳으로 보내지는 redirect-url를 추가했습니다. 
1. 최윤진 멘토님의 코드리뷰를 반영했습니다. 
- properties의 getter 관련
- Objects.nonNull() 사용
2. 로그인 중 발생하는 에러에 대해서 프론트 요청으로 error가 아닌 특정 url로 redirect하여 핸들링할 수 있도록 설정했습니다. 
3. 커피챗 상세 조회API 에 대해서 sessionUser가 null일 경우 nullPointerException이 나는데 이 에러가 ExceptionHandling 되지 않고 AuthException으로 던져지고 있어 우선은 SessionUser가 null이면 userId가 null이도록 하여 API가 동작하도록 하고 추가적으로 등록되지 않은 다른 Exception들이 모두 핸들링될 수 있는 Exception.class, 500 을 핸들링하는 핸들러를 추가했습니다. 
- closes: #271 
- closes: #297 
---
어떤 변경 사항이 …
=> Fix: request 온 host에 맞게 redirect 주소를 설정하도록 수정

module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatInfo.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/infrastructure/CoffeeChatReaderInfo.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/presentation/CoffeeChatDto.java
커피챗 목록 조회 API host 직군 항목 필드명 변경
기존 job이라는 항목명은 의미가 추상적이여서 구체적인 hostJobCategoryName으로  변경하였습니다.
- closes: #323 
---
어떤 변경 사항이 있나요?
=> Fix: 커피챗 목록 조회 API host 직군 항목 필드명 변경

module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/application/FavoriteFacade.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/core/FavoriteInfo.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/core/FavoriteInfoMapper.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/core/FavoriteReader.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/core/FavoriteService.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/core/FavoriteServiceImpl.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/infrastructure/FavoriteReaderImpl.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/infrastructure/FavoriteReaderInfo.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/infrastructure/FavoriteStoreImpl.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/presentation/FavoriteController.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/presentation/FavoriteDto.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/presentation/FavoriteDtoMapper.java, module-api/src/test/java/kernel/jdon/moduleapi/domain/favorite/application/FavoriteFacadeTest.java
- 페이징 방식 컨벤션에 맞게 변경
- 변경된 부분에 대하여 테스트 통과하도록 수정
- CustomPageResponse 방식에서 content와 pageInfo를 별도로 들고 다니는 방식으로 변경
- 찜하기/취소하기 API 
- 찜 조회하기 API
- closes: # 331
---
어떤 변경 사항이 있나요?
=> Refactor: 찜하기/취소하기, 찜 조회하기 API 페이징 변경

module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/application/JdFacade.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/core/JdInfo.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/core/JdInfoMapper.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/core/JdReader.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/core/JdService.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/core/JdServiceImpl.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/error/JdErrorCode.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/infrastructure/JdReaderImpl.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/infrastructure/WantedJdRepository.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/presentation/JdController.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/presentation/JdDto.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/presentation/JdMapper.java, module-api/src/main/java/kernel/jdon/moduleapi/global/config/auth/OAuth2SecurityConfig.java, module-api/src/main/java/kernel/jdon/wantedjd/repository/WantedJdRepository.java, module-api/src/main/resources/application-dev.yml, module-api/src/main/resources/application-local.yml, module-api/src/main/resources/application-prod.yml, module-domain/src/main/java/kernel/jdon/wantedjd/domain/WantedJd.java, module-domain/src/main/java/kernel/jdon/wantedjdskill/domain/WantedJdSkill.java
- [JD 상세조회](https://www.notion.so/JD-4e7577c6d81645deb6bab3fe32774f2d?pvs=4) API를 구현했습니다.
- WantedJd를 가져올 때 JobCategory 엔티티의 데이터를 즉시 가져올 수 있도록 WantedJd 엔티티에서 참조하고있는 JobCategory 엔티티의 참조 속성을 즉시로딩으로 변경하였습니다.
- 다대일 관계이기 때문에 항상 즉시 가져와도 문제 없다고 판단했습니다.
- JD 상세조회 API 항목에 기술스택 목록 항목이 누락되어 포함하도록 구현했습니다.
- application.yml에 batchSize를 100으로 설정했습니다.(100개 이하더라도 100개까지 조회, 나머지는 NULL로 in절에 포함됨)
API 정상 호출 확인했습니다.
- closes: #321 
---
어떤 변경 사항이 있나요?
=> Feature: JD 상세조회 API 구현

module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/infrastructure/CoffeeChatReaderImpl.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/core/FavoriteInfo.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/infrastructure/FavoriteReaderImpl.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/application/JdFacade.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/core/JdInfo.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/core/JdReader.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/core/JdService.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/core/JdServiceImpl.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/infrastructure/CustomWantedJdRepository.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/infrastructure/JdReaderImpl.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/infrastructure/JdReaderImplMapper.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/infrastructure/JdReaderInfo.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/infrastructure/WantedJdRepository.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/infrastructure/WantedJdRepositoryImpl.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/presentation/JdController.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/presentation/JdDto.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/presentation/JdDtoMapper.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/jobcategory/core/JobCategoryReader.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/core/SkillReader.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/core/SkillService.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/core/inflearnjd/InflearnJdSkillReader.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/CustomSkillRepository.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/ImplSkillRepository.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/SkillRepository.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/SkillRepositoryImpl.java, module-api/src/main/java/kernel/jdon/moduleapi/global/page/CustomJpaPageInfo.java, module-api/src/main/java/kernel/jdon/moduleapi/global/page/CustomPageInfo.java
[JD 목록 조회](https://www.notion.so/JD-bd92f83c1f284c40849e6f611896ee61?pvs=4) API 구현
- [JD 목록 조회](https://www.notion.so/JD-bd92f83c1f284c40849e6f611896ee61?pvs=4) API를 구현했습니다.
- 검색어 유무에 따른 동적쿼리를 Querydsl을 사용하여 구현했습니다.
- 인터페이스에서 매개변수에 있는 의미없는 final 키워드를 삭제했습니다.
- [domain명]RepositoryCustom 클래스 명을 Custom[domain명]Repository 형식으로 변경했습니다.
- JdMapper 인터페이스명에서 Dto가 누락되어 코드컨벤션에 맞는 JdDtoMapper로 변경하였습니다.
- CustomPageInfo 클래스를 추상화
- 기존의 CustomPageInfo 클래스를 추상화하고, `org.springframework.data.domain.Page` 라이브러리에 의존하는 Page 객체를 인자로 받는 CustomJpaPageInfo 클래스를 생성했습니다. 이에 따라 infrastructor 계층에서 CustomPageInfo를 생성자를 통해 생성하던 부분을 CustomJpaPageInfo 객체를 생성하도록 변경하였고, DTO에서는 반환타입을 추상클래스로 변경한 CustomPageInfo로 지정하였습니다. 이로써 확장성을 고려하여 다른 라이브러리를 사용하여 페이징을 구현할 때, 추상클래스를 상속받아 상세 내용을 구현할 수 있도록 수정하였습니다.(팀원들과 페어프로그래밍 진행)
- keyword …
=> Feature: JD 목록 조회 API 구현

module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/infrastructure/JdReaderImpl.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/infrastructure/JdReaderInfoMapper.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/review/application/ReviewFacade.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/review/core/ReviewCommand.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/review/core/ReviewInfo.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/review/core/ReviewReader.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/review/core/ReviewService.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/review/core/ReviewServiceImpl.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/review/core/ReviewStore.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/review/error/ReviewErrorCode.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/review/infrastructure/CustomReviewRepository.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/review/infrastructure/ReviewReaderImpl.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/review/infrastructure/ReviewReaderInfo.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/review/infrastructure/ReviewReaderInfoMapper.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/review/infrastructure/ReviewRepository.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/review/infrastructure/ReviewRepositoryImpl.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/review/infrastructure/ReviewStoreImpl.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/review/presentation/ReviewController.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/review/presentation/ReviewDto.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/review/presentation/ReviewDtoMapper.java, module-domain/src/main/java/kernel/jdon/moduledomain/review/domain/Review.java
- [리뷰 생성](https://www.notion.so/JD-3d1b6f9cf2134699b1a7f4a5a0a98ea1?pvs=4) API 구현
- [리뷰 목록조회](https://www.notion.so/JD-32527c6e72c74d9a894d67346b5a5fd6?pvs=4) API 구현
- API를 레이어드 아키텍처에 맞게 구현했습니다.
- Querydsl을 사용하는 구현체에서 필요한 DTO를 ReaderInfo로 생성했습니다.
- 캡처를 위해 size를 3으로 설정
- closes: #344 
---
어떤 변경 사항이 있나요?
=> Feature: 리뷰 목록조회, 생성 API 구현

module-api/src/main/java/kernel/jdon/member/controller/MemberController.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/member/application/MemberFacade.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/member/core/MemberCommand.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/member/core/MemberReader.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/member/core/MemberService.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/member/core/MemberServiceImpl.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/member/infrastructure/MemberReaderImpl.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/member/infrastructure/MemberStoreImpl.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/member/presentation/MemberController.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/member/presentation/MemberDto.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/member/presentation/MemberDtoMapper.java, module-domain/src/main/java/kernel/jdon/member/domain/Member.java
- `POST /api/v1/nickname/duplicate`
닉네임 중복확인하는 API를 레이어드 아키텍처에 맞게 리팩토링했습니다. 
-  existsByNickname을 사용하여 이미 사용되고 있는 닉네임인지 확인하고 사용 중이 아니라면 204를, 사용 중이라면 409 에러를 반환합니다. 
- closes: #
---
어떤 변경 사항이 있나요?
=> Refactor: 닉네임 중복 확인 API를 레이어드 아키텍처에 맞게 refactor

module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/application/CoffeeChatFacade.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatInfo.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatInfoMapper.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatService.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatServiceImpl.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/infrastructure/CoffeeChatReaderImpl.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/presentation/CoffeeChatController.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/presentation/CoffeeChatDto.java, module-api/src/test/java/kernel/jdon/moduleapi/domain/coffeechat/application/CoffeeChatFacadeTest.java, module-api/src/test/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatServiceImplTest.java, module-domain/src/main/java/kernel/jdon/coffeechat/domain/CoffeeChat.java
커피챗 상세조회시 신청여부에 따라 UI를 다르게 렌더링 하기위해 응답항목을 추가했습니다.
- AS-IS
로그인한 유저가 커피챗을 상세조회 했을 때 본인이 해당 커피챗을 신청했는지 여부를 알 수 없음
- TO-BE
상세조회 응답에 isParticipant(boolean값)을 내려주어 이미 신청한 커피챗일 경우 '신청하기' 버튼을 비활성화하여 신청여부 식별 가능
- presentation 계층에서 상세조회시 로그인 유저정보를 받습니다.
- 계층간 유저정보는 식별자(Long)로 전달합니다.  
- application, core 계층에서도 memberId를 전달받아야 하므로 인터페이스 메서드 시그니처가 변경되어 해당 내용 반영했습니다.
- 그에 따라 해당 계층 테스트코드도 수정했습니다. 
- CoffeeChatServiceImpl에서 memberId의 null 여부에 따라 분기해서 isParticipant 값을 결정하도록 했습니다.
비로그인 조회시 isParticipant에 false반환.
로그인 후 참여신청하지 않은 커피챗 조회시 isParticipant에 false반환.
로그인 후 참여신청한 커피챗 조회시 isParticipant true반환.
- closes: #348 
---
어떤 변경 사항이 있나요?
=> Feature: 커피챗 상세 조회시 응답에 로그인 유저의 기존 신청여부 추가

module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/core/JdInfo.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/core/JdInfoMapper.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/infrastructure/JdReaderImpl.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/presentation/JdDto.java, module-domain/src/main/java/kernel/jdon/wantedjd/domain/WantedJd.java
- JD 상세조회 응답 항목 reviewCount 추가
- 기술 스택 목록 중복 제거
- JD 상세조회 API의 응답 항목에 리뷰 개수 `reviewCount` 항목을 추가했습니다.
- JD 데이터 수집 시 JDON에서 사용하지 않는 기술스택인 경우`기타`로 JD에 매핑됩니다.
예를들어 5개의 기술스택이 있는데 3개의 기술스택이 JDON에서 사용하지 않는 기술스택인 경우
`JAVA, GO, 기타, Python, 기타, 기타` 와 같이 반환되고 있는 문제 상황이 있었습니다. 따라서 기술스택 목록을 반환하는 로직에서 Stream을 통해 데이터를 순회하고 distinct를 통해 중복을 제거하여 반환하도록 수정하였습니다. list를 Set으로 변환 후 다시 list로 변환할지 고민하였으나 Stream의 distinct도 내부적으로 equals를 통해 객체를 비교하고 있기 때문에 더 간략한 distinct를 사용하는 방법으로 결정하여 구현했습니다.
- closes: #353 
---
어떤 변경 사항이 있나요?
=> Fix: JD 상세조회 응답 항목 reviewCount 추가, 기술 스택 목록 중복 제거

module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatInfo.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/presentation/CoffeeChatDto.java
https://github.com/Kernel360/f1-JDON-Backend/pull/357 에서 응답 dto의 'isParticipant' 필드타입을 Boolean에서 boolean으로 수정하였습니다.
그 이후 API 테스트를 해보니 응답에서 'is' prefix가 제외되고 'participant'로만 직렬화되는 현상 발견하여 수정했습니다.
원인은 Lombok과 Jackson의 동작원리 때문입니다.
Jackson은 직렬화 할때 특정필드의 getter를 보고 필드명을 유추해서 JSON 속성을 생성합니다.
(예를 들어, member라는 필드에 getMember라는 메서드를 보고 get이라는 prefix를 제외하고 M을 소문자화해서 member라는 속성을 만듭니다.)
근데 Lombok의 @getter의 경우 필드 타입이 boolean 원시타입인 경우 getter를 is라는 prefix를 붙여 만듭니다(자바beans 규약에 따라).
그럼 Jackson이 직렬화 할때 is라는 prefix를 떼고 소문자화 하여 JSON속성을 만들기 때문에 'isParticipant'라는 필드가 'participant'로 응답이 나가게 됩니다.
각 계층별 dto에서 boolean값을 갖고 있는 필드의 getter를 직접 선언해서 롬복의 @Getter가 생성하지 않도록 했습니다.
그에 따라 Jackson이 직렬화시 'get' prefix를 제외하고 'isParticipant'로 직렬화 합니다.
- closes: #363 
---
어떤 변경 사항이 있나요?
=> BugFix: 커피챗 상세조회시 필드명 prefix 제외되는 이슈 수정

module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/application/FavoriteFacade.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/core/FavoriteFactory.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/core/FavoriteService.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/core/FavoriteServiceImpl.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/infrastructure/FavoriteFactoryImpl.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/infrastructure/FavoriteReaderImpl.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/infrastructure/FavoriteStoreImpl.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/presentation/FavoriteController.java, module-api/src/test/java/kernel/jdon/moduleapi/domain/favorite/application/FavoriteFacadeTest.java
- 찜하기/취소하기, 찜 조회하기 컨벤션에 맞게 수정했습니다.
- command, info에 final 붙이기
- factory 사용
- 메소드명 수정
- controller, service, facade (create, modify, get, remove)
- 주의: get의 경우 get + 도메인
- repository (save, find, update, delete)
- 찜 취소하기(없는 찜에 대해 취소할 경우)
- 찜 조회하기
- closes: #346
---
어떤 변경 사항이 있나요?
=> Refactor: 찜하기/취소하기, 찜 조회하기 컨벤션에 맞게 수정

module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatCommand.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatInfo.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/infrastructure/CoffeeChatReaderInfo.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/infrastructure/CoffeeChatRepositoryImpl.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/presentation/CoffeeChatDto.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/presentation/JdController.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/review/presentation/ReviewController.java
- 커피챗 도메인 DTO에 final 키워드를 추가했습니다.
- 커피챗 목록 조회 API 응답 항목에 조회수 항목을 추가했습니다.
- 커피챗 도메인 DTO에 final 키워드를 추가했습니다.
- 커피챗 목록 조회 API 응답 항목에 `viewCount` 항목을 추가했습니다.
- API 정상 호출 및`viewCount` 항목을 추가를 확인했습니다.
- closes: #315 #360 
---
어떤 변경 사항이 있나요?
=> Refactor: 커피챗 도메인 DTO에 final 키워드 추가 및 커피챗 목록 조회 API 응답 viewCount 추가

module-api/src/main/java/kernel/jdon/moduleapi/domain/review/infrastructure/ReviewRepositoryImpl.java
리뷰목록조회 시간 역순 정렬조건 추가
리뷰목록조회 메서드에 시간 역순 정렬조건을 추가했습니다.
- 첫 페이지가 가장 늦게 등록된 리뷰 순서로 조회되는 것을 확인했습니다.
- closes: #381 
---
어떤 변경 사항이 있나요?
=> Fix: 리뷰목록조회 시간 역순 정렬조건 추가

module-api/src/main/java/kernel/jdon/moduleapi/domain/member/presentation/MemberDto.java
primitive 타입 boolean을 사용하여 json key값에서 is가 빠지는 버그가 있었습니다. 
getter를 추가하여 수정했습니다. 
- closes: #373 
---
어떤 변경 사항이 있나요?
=> Fix: 로그인 상태 조회 API의 json key값 수정

module-crawler/src/main/java/kernel/jdon/modulecrawler/inflearn/service/CourseStorageService.java, module-crawler/src/main/java/kernel/jdon/modulecrawler/wanted/repository/InflearnCourseRepository.java
- 인프런 크롤링 시 기존에는 발생하지 않았던  `SQLIntegrityConstraintViolationException`가 발생했습니다.
- 원인: `findByTitle`로 인프런 강의의 존재여부를 확인하였으나, 강의중 title을 바꾼 case가 발생하여
중복임에도 불구하고 중복임을 인식하지 못해서 발생한 에러입니다.
- 해결: `title`은 변경될 여지가 있지만, 
`courseId`는 인프런에서 관리하는 unique key이기 때문에 
같은 강의에 대하여 변경될 가능성이 없습니다. 
따라서, `findByTitle` -> `findByCourseId`로 변경했습니다.
- **findByTitle -> findByCourseId**
- closes: #392
---
어떤 변경 사항이 있나요?
=> BugFix: 인프런 크롤링 에러 발생 해결

module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/presentation/CoffeeChatController.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/presentation/FavoriteController.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/presentation/JdController.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/review/presentation/ReviewController.java, module-api/src/main/java/kernel/jdon/moduleapi/global/page/PageInfoRequest.java
페이징이 필요한 API의 controller에서
```
@RequestParam(value = "page", defaultValue = "0") int page,
@RequestParam(value = "size", defaultValue = "12") int size,
```
위와같이 매개변수로 받던 페이징 변수를 
```
@ModelAttribute final PageInfoRequest pageInfoRequest
```
객체로 바인딩 되도록 수정했습니다.
- closes: #
---
어떤 변경 사항이 있나요?
=> Refactor: 공통된 page 변수들을 객체로 바인딩

module-api/src/test/java/kernel/jdon/moduleapi/domain/favorite/application/FavoriteFacadeTest.java, module-api/src/test/java/kernel/jdon/moduleapi/domain/favorite/core/FavoriteServiceImplTest.java, module-api/src/test/java/kernel/jdon/moduleapi/domain/jd/application/JdFacadeTest.java, module-api/src/test/java/kernel/jdon/moduleapi/domain/jd/core/JdServiceImplTest.java
Jd 도메인의 Facade와 ServiceImpl 단위 테스트 코드를 작성했습니다.
- 단순 조회 로직이기 때문에 모킹한 값이 잘 반환되는지를 비교했습니다.
- mock 객체이기 때문에 내부 값을 비교하기보다 존재 유무를 통해 테스트 통과 유무를 구분했습니다.
- closes: #401
---
어떤 변경 사항이 있나요?
=> Test: Jd 도메인 단위 테스트 작성 

module-api/src/main/java/kernel/jdon/moduleapi/global/validate/PastDateValidator.java, module-api/src/test/java/kernel/jdon/moduleapi/domain/member/application/MemberFacadeTest.java, module-api/src/test/java/kernel/jdon/moduleapi/domain/member/core/MemberServiceImplTest.java, module-api/src/test/java/kernel/jdon/moduleapi/domain/member/infrastructure/MemberFactoryImplTest.java
- 내 정보 조회, 수정 API에 대한 test 작성했습니다. 
- dto에서 생일날짜에 대한 유효성을 검증하는 validator에서 불필요하게 LocalDate 객체를 연달아 두번 만들고 있어서 수정했습니다. 
- MemberFacade test
- MemberService test
- MemberFactory test 
- closes: #370 
---
어떤 변경 사항이 있나요?
=> Test: 내 정보 조회 & 수정 API의 TEST code 작성

module-api/src/test/java/kernel/jdon/moduleapi/domain/member/application/MemberFacadeTest.java, module-api/src/test/java/kernel/jdon/moduleapi/domain/member/core/MemberServiceImplTest.java, module-api/src/test/java/kernel/jdon/moduleapi/domain/member/infrastructure/MemberFactoryImplTest.java
- 회원가입 API test
- 닉네임 중복 확인 API test
- member facade test
- member service test
- member factory test
- closes: #403 
---
어떤 변경 사항이 있나요?
=> Test: 회원가입, 닉네임 중복확인 API | TEST code 작성 

module-api/src/main/java/kernel/jdon/moduleapi/domain/review/core/ReviewFactory.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/review/core/ReviewServiceImpl.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/review/infrastructure/ReviewFactoryImpl.java
- 엔티티를 저장할 때 연관관계의 주인이 포함된 엔티티를 저장해야할 경우 도메인 레이어인 serviceImpl에서는 해당 도메인을 등록하라는 메시지만 보내고, 그 엔티티를 저장하기 위해 연관관계가 매핑된 엔티티를 불러오는 로직은 인프라스트럭처 레이어의 Factory 에서 구현할 수 있도록 리팩토링 했습니다.
- 기존의 리뷰를 저장하기위해 ReviewServiceImpl에서 Member와 WantedJd 엔티티를 persist후 Review를 저장했으나 해당 엔티티를 저장하기위해 데이터를 Reader하는 책임을 Factory가 가지도록 변경하고 ReviewServiceImpl 엔티티에서는 Review 엔티티를 저장하라는 메시지를 Factory에게 전달하도록  변경하였습니다.
- api 정상 동작 확인했습니다.
- closes: #405 
---
어떤 변경 사항이 있나요?
=> Refactor: Review 등록 Factory 적용

module-api/src/test/java/kernel/jdon/moduleapi/domain/member/application/MemberFacadeTest.java, module-api/src/test/java/kernel/jdon/moduleapi/domain/member/core/MemberServiceImplTest.java, module-api/src/test/java/kernel/jdon/moduleapi/domain/member/infrastructure/MemberFactoryImplTest.java
- 회원 탈퇴 API test code 작성했습니다. 
- member facade test
- member service test
- closes: #409
---
어떤 변경 사항이 있나요?
=> Test: 회원탈퇴 API | TEST code 작성

module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/application/CoffeeChatFacade.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatInfo.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatReader.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatService.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatServiceImpl.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatStore.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/error/CoffeeChatErrorCode.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/infrastructure/CoffeeChatMemberRepository.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/infrastructure/CoffeeChatReaderImpl.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/infrastructure/CoffeeChatStoreImpl.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/presentation/CoffeeChatController.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/presentation/CoffeeChatDto.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/presentation/CoffeeChatDtoMapper.java, module-domain/src/main/java/kernel/jdon/moduledomain/coffeechat/domain/CoffeeChat.java
JPA변경 감지 활용해서 커피챗 신청 취소 API를 구현했습니다.
- 엔드포인트는 신청 API와 구분위해 아래와 같이 적용했습니다
- 신청: @PostMapping("/api/v1/coffeechats/{id}")
- 취소: @PostMapping("/api/v1/coffeechats/{id}/cancel") 
- 취소 성공시 해당 커피챗의 id를 반환하며 관련 dto와 mapper를 작성했습니다.
- 전달받은 coffeeChatId와 memberId로 신청 정보가 확인 안될 시 예외를 반환합니다. 예외에 담을 에러코드 추가했습니다.
- 취소에 대한 책임은 Aggregate Root인 엔터티가 갖도록 했습니다. 취소 로직은 cascade와 orphanRemoval를 이용한 변경감지를 활용합니다. 취소 성공시 현재 모집인원을 감소시키고, 감소된 모집인원 현황에 따라 상태를 업데이트 합니다.
1번 커피챗은 모집인원이 모두 차서 '모집완료' 상태입니다.
해당 커피챗을 신청한 유저가 취소 요청에 성공하면 해당 커피챗의 식별자를 반환합니다.
취소 성공시 currentRecruitCount를 1 감소시키고 상태를 '모집중'으로 변경합니다.
유저가 신청하지 않은 커피챗에 요청시 예외를 반환합니다.
- closes: #397 
---
어떤 변경 사항이 있나요?
=> Feat: 커피챗 신청 취소 API 구현

module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/core/FavoriteServiceImpl.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/presentation/FavoriteDto.java, module-api/src/test/java/kernel/jdon/moduleapi/domain/favorite/presentation/FavoriteControllerIntegrationTest.java, module-api/src/test/resources/application.yml
- 컨트롤러 단위 테스트는 외부 요소가 많은 데에 비해 비즈니스 로직이 담겨있지 않습니다.
그렇기 때문에 단위테스트를 작성하는 의미가 적어 통합 테스트를 작성했습니다.
- 통합 테스트를 작성함으로써 API들이 제대로 작성하는지 확인하는 작업을 자동화합니다.
- 찜하기/취소하기, 찜 조회하기 컨트롤러 통합 테스트를 작성했습니다.
- `FavoriteServiceImpl`
- **favorite의 id**를 반환하는게 아니라 **찜한 강의 id**를 반환해야하므로 수정했습니다.
-  `application.yml`
- @WithMockUser를 사용하기 위해선, logoutUrl이 유효한 url형식이어야 합니다.
- 따라서, 테스트 환경에서 OAuth2SecurityConfig에서 참조하고 있는 주소를 application.yml에 추가했습니다.
- `FavoriteControllerIntegrationTest`
-  찜하기/취소하기, 찜 조회하기 컨트롤러 통합 테스트입니다.
- 유효한 요청으로 유효한 응답이 반환되는 경우: 1, 2
- 에러가 날 수 있는 경우: 3, 4
- 회원이 로그인했을 경우에만 찜하기/취소하기, 찜 조회하기 기능에 접근 가능하므로 NOT_FOUND_MEMBER에 대한 상황은 테스트하지 않았습니다.
- closes: #391 
---
어떤 변경 사항이 있나요?
=> Test: 찜하기/취소하기, 찜 조회하기 컨트롤러 통합 테스트 작성

module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/infrastructure/CoffeeChatReaderImpl.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/presentation/CoffeeChatController.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/review/application/ReviewFacade.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/review/core/ReviewInfo.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/review/core/ReviewReader.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/review/core/ReviewService.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/review/core/ReviewServiceImpl.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/review/infrastructure/CustomReviewRepository.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/review/infrastructure/ReviewReaderImpl.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/review/infrastructure/ReviewRepositoryImpl.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/review/presentation/ReviewController.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/review/presentation/ReviewDto.java, module-api/src/main/java/kernel/jdon/moduleapi/global/page/CustomJpaSliceInfo.java, module-api/src/main/java/kernel/jdon/moduleapi/global/page/CustomPageInfo.java, module-api/src/main/java/kernel/jdon/moduleapi/global/page/CustomPagingInfo.java, module-api/src/main/java/kernel/jdon/moduleapi/global/page/CustomSliceInfo.java, module-api/src/test/java/kernel/jdon/moduleapi/domain/review/application/ReviewFacadeTest.java, module-api/src/test/java/kernel/jdon/moduleapi/domain/review/core/ReviewServiceImplTest.java
리뷰 목록 조회에 no-offset 무한스크롤 페이징 방식을 적용했습니다.
무한스크롤 방식 페이징시 프론트엔드에서 필요한 항목은 `pageNumber`,`pageSize`,`last`,`empty` 네 가지 항목
페이지네이션 방식 페이징시 프론트엔드에서 필요한 항목은`pageNumber`,`pageSize`,`last`,`empty`,`totalPages`,` first` 여섯 가지 항목 입니다. (제가 퇴근 전 설명드렸던 것 처럼 무한스크롤 페이징 방식은 페이지로 이동하는 것이 아니기 때문에 첫번째 페이지 유무, 전체 페이지수가 필요하지 않습니다.)
따라서 공통된 `pageNumber`,`pageSize`,`last`,`empty` 항목을 추상클래스(CustomPagingInfo)에 정의했습니다.
**페이지네이션 방식**으로 처리하는 클래스는  `totalPages`,` first`를 필드로 갖도록 구현하고 CustomPagingInfo를 상속받아 생성자에서 모든 필드를 초기화 하도록 구현했습니다. 클래스명은 Page 객체를 사용하여 페이지네이션 방식을 처리하기 때문에 CustomPageInfo로 명명 했습니다.
**무한스크롤 방식**으로 처리하는 클래스는 CustomPagingInfo를 상속받아 생성자에서 모든 필드를 초기화 하도록 구현했으며 클래스명은 Slice 객체를 사용하여 무한스크롤 방식을 처리하기 때문에 CustomSliceInfo로 명명했습니다.
이전처럼 infrastructor 계층에서 Spring Data에 라이브러리의 Page, Slice 객체를 사용하고 있기 때문에 …
=> Fix: 리뷰 목록 조회 무한스크롤 페이징 적용

module-domain/src/main/java/kernel/jdon/moduledomain/wantedjd/domain/WantedJd.java
- wanted_jd 테이블 scraping_date 컬럼 타입 변경
- 운영서버, 개발서버의 wanted_jd 테이블의 scraping_date 컬럼 타입을 변경 했습니다.
1. DATE 타입의 TEMP 컬럼을 신규 생성
2. 기존 scraping_date 컬럼 데이터를 DATE 타입으로 형변환하여 TEMP 컬럼에 복사
3. 기존 scraping_date 컬럼을 삭제
4. TEMP 컬럼명을 scraping_date으로 변경
**개인 로컬 DB에서도 직접 DDL을 입력하여 컬럼타입 변경이 필요합니다.**
```
ALTER TABLE wanted_jd
ADD COLUMN temp DATETIME;
UPDATE wanted_jd
SET temp = STR_TO_DATE(scraping_date, '%y. %m. %d. 오후 %h:%i');
ALTER TABLE wanted_jd
DROP COLUMN scraping_date;
ALTER TABLE wanted_jd
CHANGE COLUMN temp scraping_date DATETIME;
ALTER TABLE wanted_jd
MODIFY COLUMN scraping_date DATETIME NOT NULL;
```
- WantedJd 엔티티의 scrapingDate 필드 타입을 변경했습니다.
- closes: #420 
---
어떤 변경 사항이 있나요?
=> BugFix : scrapingDate 필드 타입 변경

module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/application/CoffeeChatFacade.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatCommand.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatService.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatServiceImpl.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/error/CoffeeChatErrorCode.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/presentation/CoffeeChatController.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/presentation/CoffeeChatDtoMapper.java
- 커피챗 수정, 삭제시 로그인 유저가 작성자가 아니면 예외처리 하도록 변경했습니다.
- 각 API 컨트롤러에서 이제 로그인 유저 정보를 받습니다
- 수정 API의 경우 전달하는 파라미터가 3개가 되어서 Command DTO로 감쌌습니다.
- 본인이 작성하지 않은 커피챗을 수정,삭제하려고 할때 예외에 담을 ErrorCode를 생성했습니다.
- 그 외
- 가독성을 위한 개행 구분 및 getCoffeeChatList 메서드에서 inline variable을 바로 반환하도록 했습니다.
- 에러코드와 메서드명 네이밍을 개선했습니다.
- 에러코드: ~ALREADY_JOINED-COFFEECHAT~ -> DUPLICATE_COFFEECHAT_APPLY
- 메서드명: ~checkIfAlreadyJoined~ -> checkDuplicateApply
- 메서드명: ~checkIfMemberParticipated~ -> isParticipant
> 작성하지 않은 커피챗 수정 요청시
> 작성하지 않은 커피챗 삭제요청시
- closes: #431 
---
어떤 변경 사항이 있나요?
=> BugFix: 커피챗 수정, 삭제시 작성자 여부 Validation 추가

module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatCommand.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/core/CoffeeChatSortType.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/infrastructure/CoffeeChatRepositoryImpl.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/presentation/CoffeeChatCondition.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/presentation/CoffeeChatController.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/application/JdFacade.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/core/JdInfo.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/core/JdInfoMapper.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/core/JdReader.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/core/JdSearchType.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/core/JdSearchTypeCondition.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/core/JdService.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/core/JdServiceImpl.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/core/JdSortType.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/core/JdSortTypeCondition.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/infrastructure/CustomWantedJdRepository.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/infrastructure/JdReaderImpl.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/infrastructure/JdReaderInfo.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/infrastructure/WantedJdRepositoryImpl.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/presentation/JdCondition.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/presentation/JdController.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/presentation/JdDto.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/presentation/JdDtoMapper.java, module-api/src/main/java/kernel/jdon/moduleapi/global/config/web/WebConfig.java, module-api/src/test/java/kernel/jdon/moduleapi/domain/jd/application/JdFacadeTest.java, module-api/src/test/java/kernel/jdon/moduleapi/domain/jd/core/JdServiceImplTest.java
JD 목록 조회 API에 검색 조건을 추가했습니다. 
검색 타입이나 정렬 조건은 아무것도 입력하지 않으면 default 값이 존재해야하기에 Condition에서 아무값이 안들어오면 
keyword 타입은 title을, sort는 latest를 반환하도록 했습니다.
- `skill`
기술 스킬에 대한 검색을 제공합니다. 
- `jobCategory`
기술 스킬은 프론트엔드-자바스크립트, 백엔드-자바스크립트 와 같이 중복될 수 있어 jobCategory로 검색할 수 있도록 제공합니다. 
- `keywordType`
검색창에 검색하는 키워드의 타입을 받습니다. 
검색할 수 있는 키워드의 종류는 현재 `제목` `회사명` 이 있습니다. 
- `keyword`
검색창에 입력하는 키워드를 받고  이 키워드를 기반으로 jd 목록 조회를 지원합니다. 
- `sort`
스크래밍 날짜 최신순, 리뷰 많은 순으로 정렬하는 기능을 제공합니다. 
검색을 위한 param을 `JdCondition` 이라는 클래스로 받아서 관리합니다. 
- skill 검색
- jobCategory 검색
- keyword 검색
- 회사명 검색
- 제목 검색
- sort (스크래핑 최신순, 리뷰 많은 순)
- 리뷰 많은 순
- 2중 조건 (자바스크립트 스택의 서버 개발자면서 3년이라는 단어가 제목에 들어가도록 검색)
- closes: #383 
---
어떤 변경 사항이 있나요?
=> Feature: JD 목록조회 검색기능 구현

module-api/src/test/java/kernel/jdon/moduleapi/domain/skill/application/SkillFacadeTest.java, module-api/src/test/java/kernel/jdon/moduleapi/domain/skill/core/SkillServiceImplTest.java
Skill 도메인의 테스트코드를 리팩토링 했습니다.
- BDDMockito를 통해 검증하도록 수정했습니다.
- 테스트 코드 변수 반환 타입을 var 키워드로 변경했습니다.
- 읽기전용 변수에 final 키워드를 추가 했습니다.
- 실 객체가 아닌 mock 객체로로 검증하도록 검증방식을 변경했습니다.
테스트 정상 동작 확인했습니다.
- closes: #427 
---
어떤 변경 사항이 있나요?
=> Test: Skill 도메인 테스트코드 리팩토링

module-api/src/main/java/kernel/jdon/moduleapi/domain/auth/util/CryptoManager.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/auth/util/CryptoProperties.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/auth/util/SecretKeyConstants.java, module-api/src/main/java/kernel/jdon/moduleapi/global/config/auth/AllowOriginProperties.java, module-api/src/main/java/kernel/jdon/moduleapi/global/config/auth/OAuth2SecurityConfig.java, module-api/src/main/resources/application-dev.yml, module-api/src/main/resources/application-local.yml, module-api/src/main/resources/application-prod.yml
모니터링을 위한 메트릭 수집을 위해 actuator에서 제공하는 api에 접근해야하는데 아무곳에서나 접근하는 것을 막기 위해서 jdon의 모니터링 서버의 ip와 본인의 local에서 띄우고 local의 모니터링을 위한 localhost(0:0:0:0:0:0:0:1)을 만 허용하도록 했습니다. 
ip주소가 application.yml에서 설정해둔 ip인지 비교합니다. 
- aes, hmac에서 사용하는 key를 서버가 아니라 application.yml에서 관리하도록 수정했습니다. 
- closes: #436 
- closes: #274 
---
어떤 변경 사항이 있나요?
=> Feature: actuator를 위한 spring security 설정 

module-api/src/main/java/kernel/jdon/moduleapi/domain/auth/core/CustomOAuth2UserServiceImpl.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/auth/error/AuthErrorCode.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/member/error/MemberErrorCode.java, module-api/src/main/java/kernel/jdon/moduleapi/global/config/auth/JdonAuthExceptionHandler.java, module-api/src/main/java/kernel/jdon/moduleapi/global/config/auth/LoginRedirectUrlProperties.java, module-api/src/main/resources/application-dev.yml, module-api/src/main/resources/application-local.yml, module-api/src/main/resources/application-prod.yml, module-domain/src/main/java/kernel/jdon/moduledomain/member/domain/Member.java
1. 카카오로 회원가입 후 로그인
2. 깃허브(카카오와 같은 이메일)로 회원가입 -> 다른 소셜 로그인으로 가입한 내역 존재한다 에러.
3. 카카오 탈퇴
4. 카카오로 로그인 -> 탈퇴한 계정이다. 에러
5. 깃허브로 회원가입 -> 다른 소셜 계정으로 탈퇴한 내역이 존재한다 에러
라는 4, 5 번의 에러 상황이 있어서 error를 추가했습니다. 
다만 oauth2의 과정 중 발생하는 에러에 대해서 response가 backend의 주소(api.jdon.kr, localhost:1221 같은)로 오기 때문에 직접 redirect 해주고 있었습니다. 따라서 이 에러를 프론트에서 처리하기 위한 페이지가 존재해야합니다. 
-> 프론트와 이야기 후 redirect 주소를 추가적으로 설정, 에러에 대한 페이지 제작이 선행되어야합니다. 
- closes: #441 
---
어떤 변경 사항이 있나요?
=> Fix: OAuth2 인증 과정 중 발생할 수 있는 에러 추가

module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/presentation/CoffeeChatDto.java
정책상 커피챗 생성,수정시 오픈채팅 링크를 카카오톡 서비스로 제한함에 따라
URL입력 Validation을 해당 서비스 기준에 맞춰 수정했습니다.
공식문서에 오픈채팅 링크 생성규칙이 나와있진 않지만 직접 생성해보고 다른 링크들을 찾아보니
~.com/o/ 이후로 영어 대소문자,숫자 포함 8자리가 오는 걸로 보여서 아래의 정규식으로 검증했습니다.
https:\/\/open\.kakao\.com\/o\/[A-Za-z0-9]{8}$
카카오톡이 오픈채팅 링크 생성 규칙을 바꾸면 서비스 장애가 될 수 있으나
해당 규칙으로 가능한 경우의 수는 약 210조개로 가능성이 희박합니다.
- 생성, 수정 request dto에 validation 적용하고 message를 추가했습니다.
URL형식이 올바르지 않은 경우 예외
null인 경우 예외
빈 문자열인 경우 예외
정상 요청 및 응답
- closes: #443 
---
어떤 변경 사항이 있나요?
=> Fix: 오픈채팅 URL Validation 카카오톡 기준으로 변경

module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/SkillRepositoryImpl.java
기술스택 기반 인프런 강의 조회 SQL 질의에 중복제거 조건을 추가했습니다.
기술스택 기반 인프런 강의를 검색할 때, 연관검색어가 곂치는 기술스택일 경우 중복된 데이터가 출력되는 장애사항이 있었습니다.
장애 원인은 검색한 키워드가 연관검색어가 곂치는 기술스택일 경우 같은 기술스택의 강의 데이터를 가져오기 때문이었는데요.
이를 해결하기위해 인프런 강의 SQL조건에 `distinct`를 추가하여 중복을 제거한 3개의 데이터를 가져오도록 수정했습니다.
- closes: #468 
---
어떤 변경 사항이 있나요?
=> Bugfix: 기술스택 기반 인프런 강의 SQL 중복제거 조건 추가

module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/infrastructure/WantedJdRepositoryImpl.java, module-domain/src/main/java/kernel/jdon/moduledomain/wantedjd/domain/WantedJd.java, module-domain/src/main/java/kernel/jdon/moduledomain/wantedjd/domain/WantedJdActiveStatus.java
- 원티드 채용공고를 스크래핑하면서 마감여부를 체크하는 마감일자 및 마감여부 컬럼이 필요해 추가했습니다.
- WantedJd 엔티티가 AbstractEntity 상속받도록하여 등록일자, 수정일자 컬럼 추가를 갇도록 수정했습니다.
- 등록일자 컬럼이 추가되면서 더 이상 필요하지 않은 기존의 scraping_date 컬럼을 삭제했습니다.
- 마감일자 deadline_date 컬럼 추가
- 활성상태 active_status 컬럼 추가
- 등록일자 created_date 컬럼 추가
- 수정일자 modified_date 컬럼 추가
- 스크래핑일자 scraping_date 컬럼 삭제
기존에 운영되고 있는 테이블을 수정함에 따라 아래의 SQL 스크립트 실행이 필요합니다.
```
ALTER TABLE wanted_jd
ADD COLUMN created_date DATETIME;
```
```
UPDATE wanted_jd
SET created_date = scraping_date;
```
```
ALTER TABLE wanted_jd
MODIFY COLUMN created_date DATETIME NOT NULL;
```
```
ALTER TABLE wanted_jd
DROP COLUMN scraping_date;
```
- closes: #474 
---
어떤 변경 사항이 있나요?
=> Fix: WantedJd 엔티티 ScrapingDate 삭제 및 신규 컬럼 추가

module-crawler/src/main/java/kernel/jdon/modulecrawler/wanted/dto/response/WantedJobDetailResponse.java
- 원티드 채용공고 스크래핑 항목에 마감일자 항목 추가
- 원티드 채용공고 상세 DTO에 마감일자 `deadlineDate` 필드를 추가했습니다.
- 원티드에서는  `due_time`로 주지만 저희 서비스에서는 `deadlineDate`를 사용합니다.
- 상시채용일 경우 마감일자가 null이기 때문에 문자열인 `deadlineDate`가 null일 경우 null을 반환하고 아니라면 LocalDateTime으로 형변환하여 반환하는 getDeadlineDate 메서드를 추가했습니다.
- WantedJd 엔티티 생성 시 WantedJdActiveStatus을 OPEN 값으로 생성하도록 코드를 추가했습니다.
원티드 채용공고 상태코드, 마감일자 항목 정상 추가 확인했습니다.
- closes: #476 
---
어떤 변경 사항이 있나요?
=> Fix: 원티드 채용공고 스크래핑 항목에 마감일자 항목 추가

.github/workflows/dev-cicd.yml, module-api/src/main/java/kernel/jdon/moduleapi/domain/auth/infrastructure/KakaoOAuth2StrategyImpl.java, module-api/src/main/java/kernel/jdon/moduleapi/global/config/auth/JdonAuthExceptionHandler.java, module-api/src/main/java/kernel/jdon/moduleapi/global/config/auth/JdonOAuth2AuthenticationSuccessHandler.java, module-api/src/main/java/kernel/jdon/moduleapi/global/config/auth/OAuth2SecurityConfig.java, module-api/src/main/java/kernel/jdon/moduleapi/global/config/auth/properties/AllowOriginProperties.java, module-api/src/main/java/kernel/jdon/moduleapi/global/config/auth/properties/LoginRedirectUrlProperties.java, module-api/src/main/java/kernel/jdon/moduleapi/global/config/auth/properties/WithdrawProperties.java
- cicd event trigger 변경
- auth 관련 properties를 package로 묶어서 관리
- oauth2 인증 과정 중 발생하는 에러를 처리하는 로직을 refactor
- 이제 develop 브랜치에 push 할 때마다 개발서버에 자동 배포할 수 있습니다. 
- 만일 자동 배포하고 싶지 않다! -> label에서 NO-Deploy를 등록하시면 됩니다. 
- closes: #480 
---
어떤 변경 사항이 있나요?
=> Fix: oauth2 인증 중 error 처리 로직과 ci-cd event trigger 수정

module-crawler/src/main/java/kernel/jdon/modulecrawler/wanted/dto/response/WantedJobDetailResponse.java, module-domain/src/main/java/kernel/jdon/moduledomain/wantedjd/domain/WantedJdActiveStatus.java
- WantedJdActiveStatus 클래스'상시채용' 상수를 추가했습니다.
- 원티트 채용공고 스크래핑 시 마감일자 항목이 null로 넘어올 경우 WantedJdActiveStatus `상시채용` 상수로 바인딩하여 저장되도록 수정했습니다.
- WantedJdActiveStatus 열거형 클래스에 상시채용을 의미하는 `ALWAYS` 필드를 추가했습니다.'
- 원티트 채용공고 스크래핑 시 마감일자 항목이 null로 넘어올 경우 WantedJdActiveStatus `ALWAYS` 상수로 바인딩하여 저장되도록 수정했습니다.
- 기존에 마감일자를 체크하는 로직은 LocalDateTime.now()와 비교 했기 때문에
- 원티드에서 스크래핑한 마감일자는 문자열로 들어오기 때문에 마감일자가 2024-03-18 이라면 2024-03-18 00:00:00으로 DB에 저장하고 있었습니다. 기존 마감일자를 체크하여 원티드 채용공고 상태코드를 계산하는 로직은 LocalDateTime.now()와 2024-03-18 00:00:00 형식을 비교하여 계산했었는데, 마감 당일인경우 2024-03-18 00:00:00보다 이후이기에 잘못된 상태코드를 저장하는 장애가 있었습니다. 따라서 원티드에서 가져온 마감일자 `deadline_date`를 DB에 생성할 때 `deadlineDate` + 1 하여 등록하도록 변경했습니다.
로컬에서 스크래핑시 정상 등록 확인했습니다.
- closes: #483 
---
어떤 변경 사항이 있나요?
=> Fix: WantedJdActiveStatus `ALWAYS` 상수 추가

module-crawler/src/main/java/kernel/jdon/modulecrawler/wanted/dto/response/WantedJobDetailResponse.java, module-domain/src/main/java/kernel/jdon/moduledomain/wantedjd/domain/WantedJd.java
- WantedJd 엔티티의 생성자에 @builder 어노테이션을 제거했습니다.
- WantedJobDetailResponse에 존재하는 WantedJd의 생성 관련 로직을 WantedJd 이동 시키고 캡슐화 하였습니다.
엔티티 정상 등록 확인했습니다.
- closes: #485
---
어떤 변경 사항이 있나요?
=> Fix: WantedJd 생성 로직 캡슐화

module-api/src/main/java/kernel/jdon/moduleapi/domain/auth/util/CryptoManager.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/auth/util/CryptoProperties.java
iv의 길이가 16자 이하여야 하는데 제한을 두지 않아서 암호문을 생성하지 못하는 에러가 발생하여 수정했습니다. 
회원가입 시 info 뒤에 null로 들어오던 에러가 수정되었습니다. 
- closes: #
---
어떤 변경 사항이 있나요?
=> Hotfix: crypto manager iv 길이 에러 수정

module-crawler/build.gradle, module-crawler/src/main/java/kernel/jdon/modulecrawler/config/RestTemplateConfig.java, module-crawler/src/main/java/kernel/jdon/modulecrawler/global/error/code/CrawlerServerErrorCode.java, module-crawler/src/main/java/kernel/jdon/modulecrawler/global/error/exception/BaseThrowException.java, module-crawler/src/main/java/kernel/jdon/modulecrawler/global/error/exception/CrawlerException.java
RestTemplate Timeout을 설정 했습니다.
- 프로젝트 초반 `AppConfig`라는 이름으로 생성했던 RestTemplate을 Bean으로 등록하는 Config 클래스 파일의 이름을 `RestTemplateConfig`로 변경하였습니다.
- RestTemplate Timeout 과 Retry설정을 추가했습니다.
참고한 블로그 공유드립니다.
[[Spring] RestTemplate 타임아웃(Timeout), 재시도(Retry), 로깅(Logging) 등 설정하기](https://mangkyu.tistory.com/256)
- closes: #493 
---
어떤 변경 사항이 있나요?
=> Fix: RestTemplate Timeout 설정

module-api/src/main/java/kernel/jdon/moduleapi/domain/auth/error/AuthErrorCode.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/error/CoffeeChatErrorCode.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/error/FaqErrorCode.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/favorite/error/FavoriteErrorCode.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/inflearncourse/error/InflearncourseErrorCode.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/error/JdErrorCode.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/jobcategory/error/JobCategoryErrorCode.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/member/error/MemberErrorCode.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/review/error/ReviewErrorCode.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/error/SkillErrorCode.java, module-common/src/main/java/kernel/jdon/modulecommon/error/BaseThrowException.java, module-crawler/src/main/java/kernel/jdon/modulecrawler/global/error/code/CrawlerServerErrorCode.java, module-crawler/src/main/java/kernel/jdon/modulecrawler/global/error/exception/BaseThrowException.java
BaseThrowException common 모듈로 이동
모든 에러코드를 구현할 때 사용하는 각 모듈에 위치했던 순수 자바 인터페이스 BaseThrowException를 Common 모듈로 이동시켰습니다.
- closes: #
---
어떤 변경 사항이 있나요?
=> Chore: BaseThrowException common 모듈로 이동

module-batch/src/main/java/kernel/jdon/modulebatch/scheduler/JdScheduler.java
원티드 스크래핑 배치 스케줄링 시간 변경
원티드 스크래핑 배치 스케줄링 시간을 아래와 같이 변경 했습니다.
**부분_원티드_채용공고_스크래핑_job 스케줄러 시간 설정 :** 수요일을 제외한 모든 요일 01시
**전체_원티드_채용공고_스크래핑_job 스케줄러 시간 설정 :** 매주 수요일 01시
- closes: #521 
---
어떤 변경 사항이 있나요?
=> Fix: 원티드 스크래핑 배치 스케줄링 시간 변경

module-api/src/main/java/kernel/jdon/moduleapi/global/config/auth/OAuth2SecurityConfig.java, module-api/src/main/resources/application-dev.yml, module-api/src/main/resources/application-local.yml, module-api/src/main/resources/application-prod.yml
로드 밸런서에서 health check를 위해서 요청을 보내주는 api를 `/actuator/health`로 설정하고자 
- `/actuator/health` 를 permitAll 로 열었습니다. 
- 다만 서버 내부에 대한 정보를 최대한 숨기고자 서버의 상태만 응답 내용으로 담도록 application.yml을 수정했습니다. 
- application-profile.yml 의 health.show-details를 never로 올렸습니다. 
- `GET /actuator/health` 를 permitAll 로 전체공개했습니다. 
- closes: #516 
---
어떤 변경 사항이 있나요?
=> Fix: health check용 api securityConfig에 권한 허용

module-batch/src/main/resources/slack-appender-dev.xml, module-batch/src/main/resources/slack-appender-prod.xml
batch 모듈의 slack-appender 내부의 오타를 수정했습니다.
BATCH 모듈 내부의 CURRENT_MODULE 을 API로 잘못 표기하고 있던 부분을 수정했습니다.
- closes: #
---
어떤 변경 사항이 있나요?
=> Chore: slack-appender 오타 수정

module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/presentation/CoffeeChatController.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/presentation/JdController.java, module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/presentation/SkillController.java, module-api/src/main/java/kernel/jdon/moduleapi/global/exception/GlobalExceptionHandler.java
검색 키워드를 길게 넣었을 때 414(URI Too Long) 에러가 발생하여 20자로 제한하는 validation을 추가했습니다. 
`@RequestParam`으로 받고 있는 검색 키워드의 유효성 검증은 [다음과 같이](https://yulee.tistory.com/115) controller에 `@Validated`를 붙이고 파라미터에 직접 validation 어노테이션을 적용하면 됩니다. 
다만 이렇게 유효성 검증을 할 때 dto validation과 다르게 jakarta.validation 패키지의 `ConstraintViolationException`을 발생시킵니다. 이 Exception을 핸들링할 수 있도록 `ControllerAdvice`에 ConstraintViolationException을 핸들링하는 메서드를 추가했습니다.  
- closes: #490 
---
어떤 변경 사항이 있나요?
=> Fix: 검색 키워드 길이 제한 validation 추가

module-common/build.gradle
logback-slack-appender 의존성 추가
이전 PR #539 에서 제거했던 logback-slack-appender 의존성을 추가했습니다.
이전 PR에서 logback-slack-appender 의존성을 제거한 이유는 slack-api-client만 선언하더라도 슬랙 알림에 문제가 없었다고 판단해서인데... logback 파일에 profile이 dev일 때 logback-slack-appender를 참조하도록 slack-appender.xml에 설정되있어서 로컬 환경에서는 확인이 안됐었습니다...
이전 PR을 dev에 배포하는 과정에서 logback-slack-appender을 찾을 수 없다는 로그가 확인되어 급히 의존성을 추가했습니다.
- closes: #
---
어떤 변경 사항이 있나요?
=> Chore: logback-slack-appender 의존성 추가

module-batch/src/main/java/kernel/jdon/modulebatch/domain/coffeechat/repository/CoffeeChatRepository.java, module-batch/src/main/java/kernel/jdon/modulebatch/scheduler/CoffeeChatScheduler.java, module-domain/src/main/java/kernel/jdon/moduledomain/coffeechat/domain/CoffeeChat.java
- 배치 모듈에 만료(meetDate가 과거 날짜)된 커피챗의 상태를 변경하는 스케쥴러를 생성했습니다 
- 현재 서비스상 커피챗 생성시 meetDate를 5분 단위로 지정가능합니다. 
아래의 내용들을 고려해서 30분 단위로 지정 가능하도록 변경하고 그에 따라, 상태변경도 30분 단위로 진행하고자 합니다.
- 당일 00:00시 까지만 신청가능 하도록 하게 해서 실행 횟수를 줄이는 방법도 고려했으나 다음의 이유로 고사했습니다.
- 프론트에서 시간비교 연산을 통해 신청을 막아야 하므로 프론트에 의존적이게 된다.
- 변경 할 데이터의 볼륨이 아주커진다고 가정하면 데이터베이스의 부하를 고려해서 일 단위 보다 작은 단위로 쪼개는 것이 유리하다.
- 커피챗 서비스 특성 상 5분 단위까지 세세한 시간 구분이 필요하지 않다. 일반적으로 시간 약속을 하는 30분 단위가 적합하다고 판단.
meetDate가 현재보다 과거이면서 상태가 CLOSE가 아닌 데이터가 있는 경우
스케쥴러가 작동해서 쿼리를 실행하면
상태를 CLOSE로 변경합니다
- closes: #507 
---
어떤 변경 사항이 있나요?
=> Feature: 커피챗 만료처리 스케쥴링 적용

module-batch/src/main/java/kernel/jdon/modulebatch/scheduler/CoffeeChatScheduler.java
커피챗 meetDate 생성주기인 30분 마다 만료처리 하도록 스케쥴러 CRON식을 변경했습니다
AS-IS : 매 시각 30분마다 실행 (07:30 -> 08:30 -> 09:30)
TO-BE: 매 30분 마다 실행 (07:30 -> 08:00 -> 08:30)
- closes: #552 
---
어떤 변경 사항이 있나요?
=> fix: 커피챗 만료 스케쥴링 매 30분마다 실행하도록 변경

module-batch/src/main/java/kernel/jdon/modulebatch/job/jd/AllWantedJobScrapingJobConfig.java, module-batch/src/main/java/kernel/jdon/modulebatch/job/jd/PartWantedJdScrapingJobConfig.java, module-batch/src/main/java/kernel/jdon/modulebatch/job/jd/listener/AllBackendWantedJobScrapingJStepListener.java, module-batch/src/main/java/kernel/jdon/modulebatch/job/jd/listener/AllFrontWantedJobScrapingJStepListener.java, module-batch/src/main/java/kernel/jdon/modulebatch/job/jd/listener/AllWantedJobScrapingJobListener.java, module-batch/src/main/java/kernel/jdon/modulebatch/job/jd/listener/PartBackendWantedJobScrapingJStepListener.java, module-batch/src/main/java/kernel/jdon/modulebatch/job/jd/listener/PartFrontWantedJobScrapingJStepListener.java, module-batch/src/main/java/kernel/jdon/modulebatch/job/jd/listener/PartWantedJobScrapingJobListener.java, module-batch/src/main/java/kernel/jdon/modulebatch/job/jd/listener/UpdateJdStatusStepListener.java, module-batch/src/main/java/kernel/jdon/modulebatch/scheduler/JdScheduler.java, module-common/src/main/java/kernel/jdon/modulecommon/slack/SlackSender.java
Job, Step 실행 및 종료 시점에 슬랙 알림이 전송되도록 구현했습니다.
- **스케줄러 시작 및 종료 슬랙 알림을 Job 시작 및 종료 슬랙 알림으로 변경**
기존 스케줄러 실행 시 run 메서드 앞 뒤에 스케줄링 실행 및 종료 슬랙 알림을 보내도록 설정했었습니다.
현재는 스케줄러에 의해 Job을 실행시키지만 Job을 임의로 실행시켰을 때 Job 실행 종료 알림이 구현되어 있지 않아 해당 기능을 추가해야했었는데 스케줄링을 통해 Job이 실행되는 경우에는 결국 스케줄링에 의해 Job이 실행되므로 Job 실행 및 종료 알림을 보내는 것으로 대체해도 무관하다고 판단되어 스케줄링 알림을 Job 리스너를 활용하여 Job 알림으로 변경하였고 기존의 스케줄링 알림을 까지 보내면 너무 많은 알림이 전송되는 것 같다고 판단하여 스케줄링 알림은 삭제했습니다.
- **전체, 부분 원티드 JD 스크래핑 Job의 Step 시작 및 종료 슬랙 알림 설정**
각 스탭이 실행 종료 되는 시점에 슬랙 알림을 보내도록 Step 리스너를 통해 구현했습니다.
- 부분 원티드 Jd 스크래핑 배치 Job, Step 실행 종료 알림 
- 전체 원티드 Jd 스크래핑 배치 Job, Step 실행 종료 알림 
- closes: #547 
---
어떤 변경 사항이 있나요?
=> Feature: Job, Step 실행 및 종료 슬랙 알림 설정

module-domain/src/main/java/kernel/jdon/moduledomain/faq/domain/Faq.java, module-domain/src/main/java/kernel/jdon/moduledomain/favorite/domain/Favorite.java, module-domain/src/main/java/kernel/jdon/moduledomain/inflearnjdskill/domain/InflearnJdSkill.java, module-domain/src/main/java/kernel/jdon/moduledomain/member/domain/Member.java, module-domain/src/main/java/kernel/jdon/moduledomain/memberskill/domain/MemberSkill.java, module-domain/src/main/java/kernel/jdon/moduledomain/skill/domain/Skill.java, module-domain/src/main/java/kernel/jdon/moduledomain/skillhistory/domain/SkillHistory.java, module-domain/src/main/java/kernel/jdon/moduledomain/skillkeyword/domain/SkillKeyword.java
엔티티 @ManyToOne 필드 notnull 속성 추가
ERD상에 NOTNULL 컬럼으로 설정되어 있지만 엔티티 @ManyToOne 적용 필드 중 적용되어있지 않은 필드가 있어
`nullable = false` 속성을 추가하였습니다.
- closes: #555 
---
어떤 변경 사항이 있나요?
=> Fix: 엔티티 @ManyToOne 필드 notnull 속성 추가

module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/application/CoffeeChatFacade.java
커피챗 신청 시 동시성 제어를 위해 도입한 레디스에서 예상치 못한 동작(데드락)을 보인 경우가 있었습니다.
락 획득과 반납과정 상세한 디버깅을 위해 로그를 추가했습니다.
AS-IS: lock 획득 실패시에만 로그를 남김
TO-BE: lock 획득과 성공시에 모두 로그를 남기도록 함
- closes: #554 
---
어떤 변경 사항이 있나요?
=> fix: 커피챗 동시성 제어를 위한 락 획득과 반납 과정을 더 명확히 알기 위해 로그 추가

.github/workflows/dev-cicd.yml, .github/workflows/prev-ci.yml, .github/workflows/prod-cicd.yml
기존의 문제점
1. 기존에 [trunk based git 전략](https://helloinyong.tistory.com/335)을 사용하면서 각자의 repo에서 원본 repo로 pr을 생성했을 때 깃헙의 `secret env`를 읽어오지 못한다는 문제
2. 멀티모듈을 사용하면서 `원하는 서버만 다시 deploy` 하고 싶다는 요구사항이 생겼었습니다. 
1번 문제를 해결하려면 workflow가 동작하는 시점에서 원본 Repo의 위치여야 합니다. 
2번 문제를 해결하려면 어떤 서버를 deploy 하고자 하는지 workflow에서 판별할 수 있어야 합니다. 
push에 트리거를 걸면 2번을 해결할 수 없고, pull request에 트리거를 걸면 1번을 해결할 수 없어
버튼을 이용한 수동 트리거를 생성하고 수동 트리거의 option을 이용해서 배포하고자할 서버를 선택하도록 설정했습니다. 
원래는 github action의 트리거로 push 나 pull request를 이용했었는데 1, 2 번 문제를 모두 해결하기 위해서 Action 창에서 직접 버튼을 눌러 workflow를 동작시키는 수동 트리거를 생성했습니다. 
pr 이 머지된 후 배포하고 싶다면 
1. Action 창으로 이동한다. 
2. 동작시키고자 하는 workflow를 선택한다. 
3. 수동 트리거를 누르고 옵션을 선택한다. 
4. 배포할 서버를 선택했다면 초록색 Run workflow 버튼을 누른다. 
5. 배포되는 것을 지켜본다. 
- closes: #525 
---
어떤 변경 사항이 있나요?
=> Fix: 수동 트리거를 사용하여 deploy 하도록 수정

module-common/src/main/java/kernel/jdon/modulecommon/log/aspect/QueryCounterAspect.java
배치 Job 종료 시 Job의 SQL 실행횟수를 남기도록 AOP에 PointCut 추가
현재 존재하는 RestController 어노테이션 실행 후 SQL 실행 횟수를 로깅하는 AOP에
job 실행 후에도 SQL이 작성되도록 PointCut을 추가했습니다.
기존 API에만 로깅을 남기던 부분을 잡 실행 후에도 동일한 로깅이 추가되도록 변경했습니다.
- closes: #566 
---
어떤 변경 사항이 있나요?
=> Feat: Job 로깅 AOP PointCut 추가

module-batch/src/main/java/kernel/jdon/modulebatch/scheduler/JdScheduler.java, module-common/src/main/java/kernel/jdon/modulecommon/log/annotation/QueryCounter.java, module-common/src/main/java/kernel/jdon/modulecommon/log/aspect/QueryCounterAspect.java
[Feat: Job 로깅 AOP PointCut 추가](https://github.com/Kernel360/f1-JDON-Backend/pull/567) PR에서 추가했었던 Job 로깅 포인트컷 적용이 잘못되어 API 서버가 켜지지 않는 장애를 수정했습니다.
아래의 로그 AOP는 common모듈 QueryCounterAspect클래스에 적용되어 있습니다.
batch 서버를 구동시키면 module-batch -> module-common을 의존하는 단방향 관계로 `org.springframework.batch.core.launch.JobLauncher`라이브러리가 존재하여 batch 서버는 정상 동작하지만 
api 서버는 Spring Batch에 의존하지 않기 때문에`org.springframework.batch.core.launch.JobLauncher`포인트 컷이 적용되지 않아 API 서버를 구동하면 에러가 발생했었습니다.
[Feat: Job 로깅 AOP PointCut 추가](https://github.com/Kernel360/f1-JDON-Backend/pull/567) PR에서 테스트했을 때는 배치서버에서만 구동하고 테스트했었기에 미쳐 확인하지 못했었습니다..
따라서 common 모듈에서 `org.springframework.batch.core.launch.JobLauncher`로 AOP 포인트컷을 적용하는게 아니라 QueryCounter라는 어노테이션을 module-common 내부에 만들고 QueryCounter어노테이션이 적용된 클래스의 모든 메서드가 실행될 때 포인트컷하도록 변경하였습니다. …
=> BugFix: QueryCounter 어노테이션 생성 및 AOP 포인트컷 적용

module-batch/src/main/java/kernel/jdon/modulebatch/domain/wantedjdskill/repository/WantedJdSkillDao.java, module-batch/src/main/java/kernel/jdon/modulebatch/global/config/ScrapingWantedProperties.java, module-batch/src/main/java/kernel/jdon/modulebatch/job/jd/reader/PartBackendWantedJdItemReader.java, module-batch/src/main/java/kernel/jdon/modulebatch/job/jd/reader/PartFrontendWantedJdItemReader.java, module-batch/src/main/java/kernel/jdon/modulebatch/job/jd/reader/fetchmanager/JobDetailFetchManager.java, module-batch/src/main/java/kernel/jdon/modulebatch/job/jd/reader/fetchmanager/JobListFetchManager.java, module-batch/src/main/java/kernel/jdon/modulebatch/job/jd/writer/WantedJdItemWriter.java, module-batch/src/main/resources/constant/scraping.yml
원티드 스크래핑 배치 코드 중 오타가 발견되어 수정이 필요합니다.
- 클래스명 오타를 수정했습니다. `WantedJdSkillDto` -> `WantedJdSkillDao`
- 부분 원티드 스크래핑 배치 Reader의 중복 JD 식별 조건이 불필요하게 구현되어있어 가독성이 더 좋은 조건으로 변경했습니다.
- 원티드 스크래핑 관련 상수들이 정의되있는 `scraping.yml`의 depth를 간략화하고 이에 따른 `ScrapingWantedProperties` 클래스를 수정했습니다.
- 외부에서 메서드 체이닝으로 `ScrapingWantedProperties`의 내부 값을 사용하던 코드를 단일메서드로 사용하도록 리팩토링 했습니다.
- closes: #572 
---
어떤 변경 사항이 있나요?
=> Chore: 원티드 스크래핑 배치 코드 오타 수정 및 부분 리팩토링

module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/infrastructure/CoffeeChatRepositoryImpl.java
- 커피챗 목록조회 API에서 분리한 `id 조회 쿼리`와 `카운트 쿼리`가 항상 멤버테이블을 조인하던 것을 조인하지 않고 서브쿼리로 대체하도록 수정했습니다.
- jobCategory 조건이 없는 경우 서브쿼리를 실행하지 않도록 최적화 했습니다.
ids를 조회하는 쿼리와 totalCount를 조회하는 쿼리에서 조인문을 삭제헀습니다.
jobCategory조건이 있을 경우 where문의 서브쿼리를 통해 조회합니다. 
jobCategory조건이 없는 경우 조인없이 커피챗 테이블을 통해서만 조회하고 그 결과 커버링 인덱스가 적용됩니다.
- closes: #579 
---
어떤 변경 사항이 있나요?
=> Refactor: 커피챗 목록조회 API 동적쿼리에서 join을 서브쿼리로 대체

module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/application/CoffeeChatFacade.java, module-crawler/build.gradle, module-crawler/src/main/java/kernel/jdon/modulecrawler/domain/jd/application/JdFacade.java, module-crawler/src/main/java/kernel/jdon/modulecrawler/domain/jd/core/JdServiceImpl.java, module-crawler/src/main/java/kernel/jdon/modulecrawler/domain/jd/error/JdErrorCode.java, module-crawler/src/main/resources/application.yml, module-crawler/src/test/java/kernel/jdon/modulecrawler/domain/jd/application/JdFacadeTest.java, module-crawler/src/test/resources/application.yml
- 원티드 채용공고 스크래핑 API의 중복 실행을 방지하기 위해 동시성 제어 코드를 추가했습니다.
- scrapeWantedJd 메서드에 선언적 트랜잭션이 누락되어 `@Transaction` 어노테이션을 추가했습니다.
- pub-sub 기반의 `Redisson`을 사용하여 동시성을 제어했습니다.
- A요청에서 원티드 채용공고 스크래핑 API를 호출했을 때, A요청의 API가 종료되기 전에 다른 요청에서  원티드 채용공고 스크래핑 API를 실행할 수 없도록 구현했습니다.
- 구현한 코드 기반 테스트 코드를 작성했습니다.
- 멀티스레드 환경에서 다수의 요청이 들어와도 1개의 요청만 `scrapeWantedJd` 메서드의 락을 획득하는 테스트 코드를 추가했습니다.
- 멀티스레드 환경에서 스레드1이 `scrapeWantedJd`를 실행중일 때 스레드2에서 `scrapeWantedJd` 메서드 실행 시 예외를 반환하고 의도한 예외가 맞는지 확인하는 테스트 코드를 추가했습니다.
- 커피챗 신청에 누락된 unlock을 수정했습니다.
- closes: #577 
---
어떤 변경 사항이 있나요?
=> Fix: 원티드 채용공고 스크래핑 API 따닥 제어
