Kernel360/f1-JDON-Backend

module-api/src/main/java/kernel/jdon/ModuleApiApplication.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/controller/FaqController.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/dto/FindFaqResponse.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/entity/Faq.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/repository/FaqRepository.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/service/FaqService.java
module-api/src/main/java/kernel/jdon/moduleapi/global/common/entity/BaseEntity.java
module-api/src/main/resources/application.yml
module-api/src/test/java/kernel/jdon/moduleapi/domain/faq/service/FaqServiceTest.java

- close: #8  
어떤 변경 사항이 있나요?
PR이 다음 요구 사항을 충족하는지 확인하세요.

Feature: Faq 상세조회

---

module-api/build.gradle
module-api/src/test/java/kernel/jdon/moduleapi/domain/faq/service/FaqServiceTest.java
module-api/src/test/resources/application.yml

- 테스트 환경에서 인메모리 DB사용으로 인한 application.yml 파일 분리
- build.gradle Test H2 database 의존성 추가
- closes: #10 
어떤 변경 사항이 있나요?
PR이 다음 요구 사항을 충족하는지 확인하세요.

[Chore] 테스트환경 구축

---

module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/controller/FaqController.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/dto/request/ModifyFaqRequest.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/dto/response/ModifyFaqResponse.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/entity/Faq.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/service/FaqService.java
module-api/src/test/java/kernel/jdon/moduleapi/domain/faq/service/FaqServiceTest.java

- faq를 수정하는 API
- faq를 수정하는 service 로직을 검사하는 test code
- close: #4 
어떤 변경 사항이 있나요?
PR이 다음 요구 사항을 충족하는지 확인하세요.

Feature: Faq 수정 api 구현

---

module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/controller/FaqController.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/dto/request/UpdateFaqRequest.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/dto/response/CreateFaqResponse.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/dto/response/DeleteFaqResponse.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/dto/response/UpdateFaqResponse.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/service/FaqService.java
module-api/src/main/java/kernel/jdon/moduleapi/global/common/dto/response/CommonResponse.java
module-api/src/test/java/kernel/jdon/moduleapi/domain/faq/service/FaqServiceTest.java

- FAQ API CommonResponse 적용
- FAQ 등록 API CommonResponse 적용
- FAQ 수정 API CommonResponse 적용
- FAQ 삭제 API CommonResponse 적용
- ModifyFaqRequest -> UpdateFaqRequest 클래스명 변경 불필요 메서드 삭제
- ModifyFaqResponse -> UpdateFaqResponse 클래스명 변경
- CreateFaqResponse 필드명 수정 및 불필요 필드 삭제
- closes: #27 
---
어떤 변경 사항이 있나요?

Refector: CommonResponse 적용

---

module-common/src/main/java/kernel/jdon/dto/response/ErrorResponse.java
module-common/src/main/java/kernel/jdon/error/exception/GlobalExceptionHandler.java
module-common/src/main/java/kernel/jdon/error/exception/api/ApiException.java

- 서버에서 발생하는 예외를 핸들링 할 수 있도록 ExceptionHandler를 생성했습니다.
- ApiException이 발생 시 핸들링 하는 handlerApiException() 메서드, 정의하지 않은 모든 Exception을 핸들링하는 handlerException() 메서드를 구현했습니다.
- 에러 발생 시 반환할 필드가 정의된 ErrorResponse를 생성했습니다.
- 에러 발생 일시를 문자열 포맷으로 반환하는 getCurrentDateTimeAsString() 메서드를 구현했습니다. 
- closes: #43 
---
어떤 변경 사항이 있나요?
- [x] 새로운 기능 추가

Feature: ExceptionHandler 구현

---

module-domain/src/main/java/kernel/jdon/coffeechat/domain/CoffeeChat.java
module-domain/src/main/java/kernel/jdon/coffeechatmember/domain/CoffeeChatMember.java
module-domain/src/main/java/kernel/jdon/favorite/domain/Favorite.java
module-domain/src/main/java/kernel/jdon/inflearn/domain/Inflearn.java
module-domain/src/main/java/kernel/jdon/jobcategory/domain/JobCategory.java
module-domain/src/main/java/kernel/jdon/member/domain/Member.java
module-domain/src/main/java/kernel/jdon/memberskill/domain/MemberSkill.java
module-domain/src/main/java/kernel/jdon/skill/domain/Skill.java
module-domain/src/main/java/kernel/jdon/wanted/domain/WantedJd.java
module-domain/src/main/java/kernel/jdon/wantedskill/domain/WantedJdSkill.java

- 엔티티에 정의된 필드 중 columnDefinition이 BIGINT로 설정 된 필드에서 지정된 길이 제거
- closes: #53 
---
어떤 변경 사항이 있나요?

Bug: 엔티티 columnDefinition BIGINT 변경

---

module-domain/src/main/java/kernel/jdon/coffeechat/domain/CoffeeChat.java
module-domain/src/main/java/kernel/jdon/member/domain/Member.java

- CoffeeChat에서 필드를 추가하거나 제약조건을 추가했습니다
- Member 에서 컬렉션으로 된 필드 자료형을 수정했습니다.
- CoffeeChat 엔터티
- CoffeeChatMember 연결테이블 엔터티를 참조하는 필드를 추가했습니다.
- nullable false 제약조건과 default value 설정을 필요한 필드들에 적용했습니다
- Member 엔터티에 컬렉션 자료형이 ArrayList로 선언된 필드들을 List로 수정했습니다.
- closes: #74 
---
어떤 변경 사항이 있나요?

Refactor: 커피챗과 멤버 엔터티 필드 및 제약조건 수정

---

module-api/src/main/java/kernel/jdon/member/controller/MemberController.java
module-domain/src/main/java/kernel/jdon/member/dto/request/ModifyMemberRequest.java
module-domain/src/main/java/kernel/jdon/member/dto/request/NicknameDuplicateRequest.java
module-domain/src/main/java/kernel/jdon/member/dto/request/SaveMemberRequest.java
module-domain/src/main/java/kernel/jdon/member/dto/response/GetMemberResponse.java
module-domain/src/main/java/kernel/jdon/member/dto/response/ModifyMemberResponse.java
module-domain/src/main/java/kernel/jdon/member/dto/response/RemoveMemberResponse.java
module-domain/src/main/java/kernel/jdon/member/dto/response/SaveMemberResponse.java

가데이터를 반환하는 마이페이지 관련 API 구현
- 내 정보 등록하기 API (회원가입) : https://www.notion.so/e9836bcb0fa841149535e1c4afd57b13?pvs=4
- 내 정보 가져오기 API : https://www.notion.so/961ea652d8024210ba5a24f89ba09c2b?pvs=4
- 내 정보 수정하기 API : https://www.notion.so/62f850f7ed294911bddd682507835271?pvs=4
- 내 정보 삭제하기 API (회원탈퇴) : https://www.notion.so/6b7d5f42c61e4c4c80ef804cef395943?pvs=4
- 내 닉네임 중복 확인하기 API : https://www.notion.so/bc2e594b1c284bd58a2b4be4d5690984?pvs=4
- POST  /api/v1/member
- GET  /api/v1/member
- PUT  /api/v1/member
- DELETE  /api/v1/member
- POST  /api/v1/member
- closes: #64 
---
어떤 변경 사항이 있나요?

Feature: 마이페이지 관련 가데이터 내려주는 API 구현

---

module-api/src/main/java/kernel/jdon/coffeechat/controller/CoffeeChatController.java
module-domain/build.gradle
module-domain/src/main/java/kernel/jdon/coffeechat/dto/request/CreateCoffeeChatRequest.java
module-domain/src/main/java/kernel/jdon/coffeechat/dto/request/UpdateCoffeeChatRequest.java
module-domain/src/main/java/kernel/jdon/coffeechat/dto/response/ApplyCoffeeChatResponse.java
module-domain/src/main/java/kernel/jdon/coffeechat/dto/response/CreateCoffeeChatResponse.java
module-domain/src/main/java/kernel/jdon/coffeechat/dto/response/DeleteCoffeeChatResponse.java
module-domain/src/main/java/kernel/jdon/coffeechat/dto/response/FindCoffeeChatListResponse.java
module-domain/src/main/java/kernel/jdon/coffeechat/dto/response/FindCoffeeChatResponse.java
module-domain/src/main/java/kernel/jdon/coffeechat/dto/response/UpdateCoffeeChatResponse.java

프론트에서 병렬적으로 개발할 수 있도록
커피챗 관련 API 가데이터 응답 구현
*상세조회와 등록하기는 가데이터가 아닌 기존 구현된 내용입니다.
*상세조회시에 job필드가  null로 되어있는데 이는 CoffeChat엔터티가 JobCategory랑 연관관계가 안되어 있어서
따로 이슈를 파서 수정할 예정입니다!
- 내가 신청한 커피챗 목록 조회 https://www.notion.so/abd1dbae0f28477687ec95e3ccfd2b4f?pvs=4
- 내가 오픈한 커피챗 목록 조회 https://www.notion.so/2d2007b651764ac290a25b4c38fe929b?pvs=4
- 전체 커피챗 목록 조회 https://www.notion.so/7c7962a4b1104cc5a6a79d172596863c?pvs=4
- 커피챗 상세 조회 https://www.notion.so/f39da55def4144bf9583b27b6caaca7c?pvs=4
- 커피챗 등록하기 https://www.notion.so/88e4293db39e407692719b94673cdef1?pvs=4
- 커피챗 수정하기 https://www.notion.so/f072f8ab837545a3a34aa763263c20bf?pvs=4
- 커피챗 삭제하기 https://www.notion.so/6342819e0730474e96954a64270e072d?pvs=4
- 커피챗 신청하기 https://www.notion.so/771acd3362164145bf9ea8c91d638fa2?pvs=4
- 내가 신청한 커피챗 목록
- 내가 오픈한 커피챗 …

Feature: CoffeeChat 관련 가데이터 응답 API

---

module-common/src/main/java/kernel/jdon/error/code/crawler/WantedErrorCode.java
module-crawler/src/main/java/kernel/jdon/crawler/wanted/service/WantedCrawlerService.java
module-domain/src/main/java/kernel/jdon/skill/domain/Skill.java

- #97 PR의 리뷰에 대한 수정사항 적용
- 브랜치 오류로 인해 부득이 하게 변경사항에 대한 PR을 다시 생성하였습니다.
- WantedErrorCode 상수 오타 수정
- createSkills 메서드를 컨벤션에 따라 createSkillList로 변경
- skill 엔티티의 오타였던 ``final`` 키워드 제거
```
private final List<WantedJdSkill> wantedJdSkillList = new ArrayList<>();
```
```
privat List<WantedJdSkill> wantedJdSkillList = new ArrayList<>();
```
- closes: #
---
어떤 변경 사항이 있나요?

Fix: Apply feedback from code review

---

module-api/src/main/java/kernel/jdon/coffeechat/controller/CoffeeChatController.java
module-api/src/main/java/kernel/jdon/coffeechat/service/CoffeeChatService.java
module-common/src/main/java/kernel/jdon/error/code/api/CoffeeChatErrorCode.java
module-domain/build.gradle
module-domain/src/main/java/kernel/jdon/coffeechat/domain/CoffeeChat.java

커피챗 수정 로직과 API를 구현했습니다.
- 커피챗 엔터티
- 비즈니스 로직 검증 
- 커피챗 모집인원 유효성 검증
- 커피챗 일자 유효성 검증
- 커피챗 모집인원에 따른 상태 변경
- 도메인 모듈에서 공용 ApiException 사용을 위해 CommonModule 의존성 추가  
- 에러코드
- 비즈니스 로직 작성에 따른 에러코드 Enum을 추가했습니다. 
- 수정로직 추가에 따른 Controller와 Service 변경.
- closes: #99 
---
어떤 변경 사항이 있나요?

Feature: 커피챗 수정 API 구현

---

module-crawler/src/main/java/kernel/jdon/crawler/wanted/controller/WantedCrawlerController.java
module-crawler/src/main/java/kernel/jdon/crawler/wanted/converter/EntityConverter.java
module-crawler/src/main/java/kernel/jdon/crawler/wanted/service/WantedCrawlerService.java
module-domain/src/main/java/kernel/jdon/wantedjd/domain/WantedJd.java

- WantedJd 테이블 컬럼 추가
- 크롤링 시 해당 컬럼에 데이터 추가되도록 구현
- 원티드 상세 페이지에서 가져올 수 있는 정보를 저장하기 위해 아래의 컬럼 추가하였습니다.
- 자격요건
- 우대사항
- 주요업무
- 혜택 및 복지
- closes: #127 
---
어떤 변경 사항이 있나요?

Feature: WantedJd 테이블 컬럼 추가 및 변경 사항 적용

---

module-api/src/main/java/kernel/jdon/jobcategory/controller/JobCategoryController.java
module-api/src/main/java/kernel/jdon/jobcategory/dto/response/FindListJobGroupResponse.java
module-api/src/main/java/kernel/jdon/jobcategory/repository/JobCategoryRepository.java
module-api/src/main/java/kernel/jdon/jobcategory/service/JobCategoryService.java

[직군 별 직무 조회](https://www.notion.so/a49395c98c8849f8b1e9d3f3de72c97a?pvs=4) API 구현
- 직군 별 직무 조회 API를 구현하였습니다.
- closes: #168 
---
어떤 변경 사항이 있나요?

Feature: 직군 별 직무 조회 API 구현

---

module-api/src/main/java/kernel/jdon/config/auth/JdonOAuth2AuthenticationSuccessHandler.java

이미 회원인 사람이 oauth 로그인했을 때 성공하면 넘어가는 redirect url을 추가했습니다. 
- closes: #208
---
어떤 변경 사항이 있나요?

BugFix: 로그인 성공시 redirect 주소 추가

---

module-api/src/main/java/kernel/jdon/config/auth/JdonOAuth2AuthenticationSuccessHandler.java

- closes: #
---
어떤 변경 사항이 있나요?

Fix: 리다이렉트 url을 URL encoding 추가

---

module-api/src/main/java/kernel/jdon/config/auth/OAuth2SecurityConfig.java

cors 옵션 추가했습ㄴㅣ다
- closes: #
---
어떤 변경 사항이 있나요?

Feature: add cors options

---

module-api/src/main/java/kernel/jdon/coffeechat/controller/CoffeeChatController.java
module-api/src/main/java/kernel/jdon/config/auth/OAuth2SecurityConfig.java
module-api/src/main/java/kernel/jdon/favorite/controller/FavoriteController.java
module-api/src/main/java/kernel/jdon/member/controller/MemberController.java
module-api/src/main/java/kernel/jdon/skill/controller/SkillController.java

api 요청시 쿠키가 안담기는 이슈로 인해 오늘 하루만 잠시 2로 고정된 userId 로 api가 동작하도록 조치했습니다. 
- closes: #219 
---
어떤 변경 사항이 있나요?

Fix: 프론트 test를 위한 임시 userId 세팅

---

module-api/build.gradle

- fixture-monkey 라이브러리 추가
- 원활한 테스트코드 작성을 위한 테스트 객체 생성 라이브러리 [fixture-monkey](https://github.com/naver/fixture-monkey) 의존성 추가
- 아래의 라이브러리가 추가된 것을 확인했습니다.
- closes: #227 
---
어떤 변경 사항이 있나요?

Setting: fixture-monkey 라이브러리 추가

---

module-api/src/main/resources/application-dev.yml

application-dev.yml
localhost:3000에서 개발하는 프론트 분들이 핸들링할 수 있도록 
- 프론트로 redirect하는 주소의 hostname은 localhost:3000,
- oauth 서버에서 redirect 하는 주소는 배포 인스턴스의 ip로 설정된 dev용 application.yml을 추가했습니다. 
- application-prod.yml 은 정말 서비스 운영을 위한 application.yml이라고 보시면 됩니다. 
- closes: #230
---
어떤 변경 사항이 있나요?

Bugfix: 개발용 배포환경을 위한 application.yml 추가 

---

module-api/src/main/java/kernel/jdon/config/auth/OAuth2SecurityConfig.java
module-api/src/main/resources/application-dev.yml
module-api/src/main/resources/application-prod.yml
module-api/src/main/resources/application.yml

- 새로 생성한 api.jdon.kr 과 jdon.kr 을 정책에 추가했습니다. 
- cors  allow origin
- application.yml redirect url
- closes: #
---
어떤 변경 사항이 있나요?

Fix: cors 정책과 application.yml에 새로운 도메인 네임 적용

---

module-api/src/main/java/kernel/jdon/auth/service/JdonOAuth2UserService.java
module-api/src/main/java/kernel/jdon/coffeechat/controller/CoffeeChatController.java
module-api/src/main/java/kernel/jdon/coffeechat/dto/request/CreateCoffeeChatRequest.java
module-api/src/main/resources/application-dev.yml
module-api/src/main/resources/application.yml

- closes: #
---
어떤 변경 사항이 있나요?

Fix: QA를 위한 로거 추가 

---

module-api/src/main/java/kernel/jdon/coffeechat/dto/request/UpdateCoffeeChatRequest.java
module-api/src/main/java/kernel/jdon/coffeechat/error/CoffeeChatErrorCode.java
module-api/src/main/java/kernel/jdon/coffeechat/service/CoffeeChatService.java
module-domain/src/main/java/kernel/jdon/coffeechat/domain/CoffeeChat.java

커피챗 수정로직 에러코드를 구체화하고 가독성을 개선했습니다.
- UpdateCoffeeChatRequest 클래스
- 불필요한 스태틱 메서드를 인스턴스 메서드로 변경했습니다.
- CoffeeChatErrorCode 클래스
- Enum을 구체화 했습니다.
- 업데이트 요청 dto를 캐스팅한 엔터티의 변수명을 target -> updateCoffeeChat 으로 수정했습니다.
- checkMeetDate 메서드
- 인자를 받는 대신 인스턴스 상태를 활용하고 변수명을 수정해 가독성을 개선했습니다.
- checkTotalRecruitCount 메서드
- 메서드명 checkRecruitCount -> checkTotalRecruitCount로 검증하는 값을 구체적으로 표기 했습니다.
- 모집인원 검증에서 일정관련 에러를 던지는 내용을 수정했습니다.
- closes: #244 
---
어떤 변경 사항이 있나요?

Refactor: 커피챗 수정 API 리팩토링

---

module-api/src/main/java/kernel/jdon/config/auth/OAuth2SecurityConfig.java
module-api/src/main/java/kernel/jdon/favorite/controller/FavoriteController.java

프론트 test를 위해서 favorite 강의잠시 인증 안거치도록 오픈했습니다.
- closes: #
---
어떤 변경 사항이 있나요?

fix: open auth api for test

---

module-api/src/main/java/kernel/jdon/auth/service/LoginUserArgumentResolver.java
module-api/src/main/java/kernel/jdon/config/auth/OAuth2SecurityConfig.java

- closes: #
---
어떤 변경 사항이 있나요?

Fix: auth open for 프론트 test

---

README.md

- closes: #
---
어떤 변경 사항이 있나요?

Docs: Modify image path

---

.github/CODEOWNERS

- closes: #
---
어떤 변경 사항이 있나요?

Chore: Set auto assign reviewer

---

module-api/build.gradle
module-api/src/main/java/kernel/jdon/application/faq/FaqFacade.java
module-api/src/main/java/kernel/jdon/application/faq/FaqReader.java
module-api/src/main/java/kernel/jdon/application/faq/FaqStore.java
module-api/src/main/java/kernel/jdon/domain/faq/FaqCommand.java
module-api/src/main/java/kernel/jdon/domain/faq/FaqInfo.java
module-api/src/main/java/kernel/jdon/domain/faq/FaqService.java
module-api/src/main/java/kernel/jdon/domain/faq/FaqServiceImpl.java
module-api/src/main/java/kernel/jdon/faq/controller/FaqController.java
module-api/src/main/java/kernel/jdon/faq/repository/FaqRepository.java
module-api/src/main/java/kernel/jdon/faq/service/FaqService.java
module-api/src/main/java/kernel/jdon/global/exception/GlobalExceptionHandler.java
module-api/src/main/java/kernel/jdon/infrastructure/faq/FaqReaderImpl.java
module-api/src/main/java/kernel/jdon/infrastructure/faq/FaqRepository.java
module-api/src/main/java/kernel/jdon/infrastructure/faq/FaqStoreImpl.java
module-api/src/main/java/kernel/jdon/interfaces/faq/FaqController.java
module-api/src/main/java/kernel/jdon/interfaces/faq/FaqDto.java
module-api/src/main/java/kernel/jdon/interfaces/faq/FaqDtoMapper.java
module-common/src/main/java/kernel/jdon/dto/response/ErrorResponse.java

[The RED : 비즈니스 성공을 위한 Java/Spring 기반 서비스 개발과 MSA 구축 by 이희창](https://2024fastcampus.skillflo.io/classroom/11096/10108/content/21513)
강의에서의 DDD 패턴을 FAQ 도메인에 시범 적용 했습니다.
상세 내용은 차주 회의 때 설명드리겠습니다.
- closes: #275 
---
어떤 변경 사항이 있나요?

Refactor: FAQ DDD 패턴 적용

---

module-api/src/main/resources/application-dev.yml
module-api/src/main/resources/application-prod.yml
module-api/src/main/resources/application.yml

- 서버에서 레디스 비밀번호를 필요로 하여 yml 파일에 해당 property 추가했습니다. 
- 프론트 개발 환경을 위해서 cookie same-site = none 옵션을 추가했습니다. 
- closes: #
---
어떤 변경 사항이 있나요?

Fix: redis properties yml에 추가

---

module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/application/SkillFacade.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/application/SkillReader.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/core/SkillCommand.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/core/SkillInfo.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/core/SkillReader.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/core/SkillService.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/core/SkillServiceImpl.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/error/SkillErrorCode.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/SkillReaderImpl.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/SkillReaderInfo.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/SkillRepository.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/SkillRepositoryCustom.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/SkillRepositoryImpl.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/presentation/SkillController.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/presentation/SkillDto.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/presentation/SkillDtoMapper.java
module-api/src/main/java/kernel/jdon/skill/controller/SkillController.java
module-api/src/main/java/kernel/jdon/skill/repository/SkillRepository.java
module-api/src/main/java/kernel/jdon/skill/repository/SkillRepositoryImpl.java
module-api/src/main/java/kernel/jdon/skill/service/SkillService.java
module-api/src/test/java/kernel/jdon/faq/service/FaqServiceTest.java
module-api/src/test/java/kernel/jdon/faq/service/SkillServiceTest.java
module-api/src/test/java/kernel/jdon/moduleapi/domain/skill/application/SkillFacadeTest.java
module-api/src/test/java/kernel/jdon/moduleapi/domain/skill/core/SkillServiceImplTest.java

인기있는 기술스택 조회 API, 회원 기술 스택 조회 API 추상화하여 리팩토링
-  인기있는 기술스택 조회 API, 회원 기술 스택 조회 API를 계층별로 추상화를 적용하였습니다.
- layered architecture 기반의 패키지로 분할 후 추상클래스 및 구현클래스를 각 위치 시켰습니다.
- Facade와 ServiceImpl 클래스의 테스트 코드를 작성했습니다.
- Facade 테스트 실행 결과
- ServiceImple 테스트 결과
---
- 인기있는 기술스택 조회 정상 실행
---
- 회원 기술 스택 조회 정상 실행
- closes: #286 
---
어떤 변경 사항이 있나요?

Refactor: 인기있는 기술스택 조회 API, 회원 기술 스택 조회 API 추상화 리팩토링

---

module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/core/FaqReader.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/core/FaqServiceImpl.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/core/FaqStore.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/infrastructure/FaqReaderImpl.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/faq/infrastructure/FaqStoreImpl.java

- FaqReader과 FaqStore를 이동시켰습니다
- closes: #309 
---
어떤 변경 사항이 있나요?

Refactor: Faq 패키지 구조 변경

---

module-domain/src/main/java/kernel/jdon/moduledomain/review/domain/Review.java
module-domain/src/main/java/kernel/jdon/moduledomain/review/repository/ReviewDomainRepository.java

- Review 엔티티 생성
- Review 엔티티를 생성했습니다.
- 다대일 관계인 Member 엔티티와 연관관계를 설정했습니다.
- 다대일 관계인 Wantedjd 엔티티와 연관관계를 설정했습니다.
- ReviewDomainRepository를 생성했습니다.
ddl-auto가 update로 설정되있어서 신규 엔티티 추가 후 서버 구동 시 아래와 같이 테이블이 생성된 것을 확인했습니다.
- closes: #328 
---
어떤 변경 사항이 있나요?

Feature: Review 엔티티 생성

---

module-api/src/main/java/kernel/jdon/moduleapi/domain/review/application/ReviewFacade.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/review/core/ReviewCommand.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/review/core/ReviewReader.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/review/core/ReviewService.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/review/core/ReviewServiceImpl.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/review/core/ReviewStore.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/review/error/ReviewErrorCode.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/review/infrastructure/ReviewReaderImpl.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/review/infrastructure/ReviewStoreImpl.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/review/presentation/ReviewController.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/review/presentation/ReviewDtoMapper.java

[리뷰 삭제](https://www.notion.so/JD-4ea3f54fb44d4bffa0a94cb5e2844f14?pvs=4) API를 구현 했습니다.
API를 레이어드 아키텍처에 맞게 구현했습니다.
- closes: #349 
---
어떤 변경 사항이 있나요?

Feature: 리뷰 삭제 API 구현

---

module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/presentation/CoffeeChatController.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/presentation/CoffeeChatDto.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/review/presentation/ReviewDto.java

커피챗과 리뷰 등록,수정시 request DTO에 validation을 적용했습니다.
기준은 아래와 같이 일단 정했습니다. 수정이 필요할 경우 논의하여 반영하겠습니다.
- 커피챗
- 제목
- 10자 이상 50자 이하 
- 내용
-  50자 이상 500자 이하
- 모집인원
- 1명 이상 100명 이하 
- 일시
- 현재보다 미래 시점
-  오픈채팅 링크
- URL 형식 준수
- 리뷰
- 내용
-  10자 이상 500자 이하
각 도메인 request DTO에 적용했습니다
제목 조건 미준수
내용 조건 미준수
모집인원 조건 미준수
일시 조건 미준수
URL형식 미준수
- closes: #376 
---
어떤 변경 사항이 있나요?

Feature: 커피챗, 리뷰 DTO Validation 반영

---

module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/SkillKeywordManager.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/SkillRepositoryImpl.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/presentation/SkillController.java
module-domain/src/main/java/kernel/jdon/moduledomain/skill/domain/SkillType.java

연관 검색어 키워드 조회 메서드 명 변경 및 메서드 설명 추가
연관 검색어 키워드 조회 소스에서 메서드 명을 더 명확한 의미로 변경하고 복잡한 프로세스를 다루고 있는 메서드에 설명을 추가했습니다.
- closes: #
---
어떤 변경 사항이 있나요?

Fix: 연관 검색어 키워드 조회 메서드 명 변경 및 메서드 설명 추가

---

module-api/src/test/java/kernel/jdon/moduleapi/domain/review/application/ReviewFacadeTest.java
module-api/src/test/java/kernel/jdon/moduleapi/domain/review/core/ReviewServiceImplTest.java
module-api/src/test/java/kernel/jdon/moduleapi/domain/review/infrastructure/ReviewFactoryImplTest.java
module-api/src/test/resources/giventest/review/serviceimpl/1_review.json
module-domain/src/main/java/kernel/jdon/moduledomain/review/domain/Review.java

- Review 도메인 단위 테스트 코드를 작성했습니다.
- ReviewFacade 단위 테스트 코드를 작성했습니다.
- ReviewServiceImpl 단위 테스트 코드를 작성했습니다.
- Review 엔티티의 id 생성자가 없는 관계로 ObjectMapper를 통해 엔티티를 생성했습니다. 
- ReviewFactory 단위 테스트 코드를 작성했습니다.
- 기존에 사용하던 Mockito 라이브러리가 아닌 BDDMockito로 변경하여 테스트를 검증했습니다.
- Review 도메인의 단위테스트를 실행한 결과 정상 작동을 확인했습니다.
- closes: #406 
---
어떤 변경 사항이 있나요?

Test: Review 도메인 단위 테스트 코드 작성

---

module-api/src/main/resources/application-dev.yml

백엔드 개발 서버의 도메인 주소 변경으로 인해 oauth2 redirect 주소가 변경되어 수정했습니다.
kakao, github oauth2 앱에 redirect url을 수정하였습니다. 
- closes: #458 
---
어떤 변경 사항이 있나요?

Fix: 개발 서버의 oauth2 redirect 주소 변경하기

---

module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/core/JdReader.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/core/JdServiceImpl.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/infrastructure/CustomWantedJdRepository.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/infrastructure/JdReaderImpl.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/infrastructure/WantedJdRepositoryImpl.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/presentation/JdCondition.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/core/SkillReader.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/core/SkillServiceImpl.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/core/inflearnjd/InflearnJdSkillReader.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/core/keyword/SkillKeywordReader.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/core/wantedjd/WantedJdSkillReader.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/CustomSkillRepository.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/SkillReaderImpl.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/SkillRepositoryImpl.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/inflearnjd/InflearnJdSkillReaderImpl.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/keyword/SkillKeywordReaderImpl.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/keyword/SkillKeywordRepository.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/infrastructure/wantedjd/WantedJdSkillReaderImpl.java
module-api/src/test/java/kernel/jdon/moduleapi/domain/jd/core/JdServiceImplTest.java
module-api/src/test/java/kernel/jdon/moduleapi/domain/skill/core/SkillServiceImplTest.java
module-domain/src/main/java/kernel/jdon/moduledomain/skillkeyword/domain/SkillKeyword.java

메인화면 및 JD 목록에서 기술스택 기반으로 검색할 때, 연관어로 검색한다면 해당 연관어를 포함하고있는 기술스택 목록을 조회할 수 있도록 수정했습니다.
- 연관어 목록을 가져오는 객체를 호출하는 부분을 infrastructor 계층이 아닌 domain 계층에서 호출하도록 변경했습니다.
- 연관어를 검색했을 경우 domain 계층에서 해당 연관어를 포함하고있는 origin 기술스택 목록을 가져오고 이를 infrastructor 계층으로 전달하여 SQL 질의를 통해 해당 연관어를 포함하고 있는 기술스택 목록을 기반으로 데이터를 가져오도록 변경했습니다.
- serviceImpl에 호출하는 메서드가 추가됨에 따라 테스트 코드에 추가된 메서드를 mocking하는 코드를 추가했습니다. 
연관어 `언어`를 포함하고 있는 기술스택의 목록을 기반으로 검색합니다.
연관어 `자바`를 포함하고 있는 기술스택 기반으로 검색합니다.
연관어 `언어`를 포함하고 있는 기술스택의 목록을 기반으로 검색합니다.
연관어 `고`를 포함하고 있는 기술스택 기반으로 검색합니다.
- closes: #460 
---
어떤 변경 사항이 있나요?

Fix: 기술스택 연관어 목록으로 검색하도록 수정

---

.github/workflows/prod-cicd.yml

- closes: #
---
어떤 변경 사항이 있나요?

Feature: 운영 서버용 ci cd 구축

---

.github/workflows/dev-cicd.yml

- closes: #
---
어떤 변경 사항이 있나요?

test: test cicd for secret enviroment

---

.github/workflows/dev-cicd.yml

- closes: #
---
어떤 변경 사항이 있나요?

Test: test cicd for secret enviroment and event trigger

---

module-common/src/main/java/kernel/jdon/modulecommon/util/DateParserUtil.java

main 브랜치에 Hotfix로 merge한 #511 이슈의 내용을 dev 브랜치에 병합하기 위한 PR입니다.
- closes: #510
---
어떤 변경 사항이 있나요?

Hotfix: DateParserUtil localDateTimeToDateString 날짜 처리 수정

---

module-batch/src/main/java/kernel/jdon/ModuleBatchApplication.java
module-batch/src/main/java/kernel/jdon/modulebatch/job/course/InflearnCourseScrapingJobConfig.java
module-batch/src/main/java/kernel/jdon/modulebatch/scheduler/InflearnScheduler.java

- 잡과 스텝의 이름을 한국어 -> 영어로 바꿨습니다.
- 이름 바꾸면서 확인해본 결과, 마지막 페이지 로직이 제대로 작동하지 않아서 스케줄러 돌리는 부분을 주석처리하고 올리겠습니다.
- closes: #513 
---
어떤 변경 사항이 있나요?

Fix: 인프런 크롤링 스케줄러

---

module-api/src/main/resources/slack-appender-dev.xml
module-api/src/main/resources/slack-appender-prod.xml

API 모듈의 슬랙 알림 로그 레벨을 WARN에서 ERROR로 상향 조정
API 모듈의 슬랙 알림 로그 레벨을 WARN에서 ERROR로 상향 조정했습니다.
- closes: #
---
어떤 변경 사항이 있나요?

Chore: 슬랙 알림 로그 레벨 ERROR로 수정

---

module-batch/src/main/resources/slack-appender-dev.xml
module-batch/src/main/resources/slack-appender-prod.xml

- closes: #
---
어떤 변경 사항이 있나요?

Chore: slack-appender 오타 수정 (#536)

---

module-api/src/main/java/kernel/jdon/ModuleApiApplication.java
module-batch/src/main/java/kernel/jdon/ModuleBatchApplication.java
module-batch/src/main/java/kernel/jdon/modulebatch/scheduler/JdScheduler.java
module-batch/src/main/resources/slack-appender-dev.xml
module-batch/src/main/resources/slack-appender-prod.xml
module-common/build.gradle
module-common/src/main/java/kernel/jdon/modulecommon/slack/SlackMessage.java
module-common/src/main/java/kernel/jdon/modulecommon/slack/SlackSender.java

슬랙 알림 전송 기능을 구현했습니다.
* 슬랙 알림 전송 기능 구현
- SlackMessage
- 슬랙에 알림을 보낼 value를 담는 객체입니다. of 메서드 통해 매개변수 알림 제목을 초기화합니다.
- 보낼 상세 내용은 putMessage 메서드, 알림 색상은 setColor으로 설정할 수 있으며 메서드 체이닝 하여 사용할 수 있습니다.
- SlackMessage를 생성 후 SlackSender의 sendMessage 메서드를 호출하면 다음과 같이 채널에 알림이 전송됩니다.
* 모듈별 서버 실행 시 슬랙 알림을 보내도록 구현했습니다. Application가 켜진 후 실행할 수 있도록 ApplicationRunner를 implement하여 슬랙 알림을 보내도록 구현했습니다.
* 배치 스케줄러 시작 시 슬랙 알림으로 전송될 수 있도록 구현했습니다.
위 사진 참조
- closes: #520 
---
어떤 변경 사항이 있나요?

Feature: 슬랙 알림 전송 기능 구현

---

module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/presentation/CoffeeChatController.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/jd/presentation/JdController.java
module-api/src/main/java/kernel/jdon/moduleapi/domain/skill/presentation/SkillController.java
module-api/src/main/java/kernel/jdon/moduleapi/global/config/auth/OAuth2SecurityConfig.java
module-api/src/main/java/kernel/jdon/moduleapi/global/exception/GlobalExceptionHandler.java
module-api/src/main/resources/application-dev.yml
module-api/src/main/resources/application-local.yml
module-api/src/main/resources/application-prod.yml
module-api/src/main/resources/slack-appender-dev.xml
module-api/src/main/resources/slack-appender-prod.xml
module-batch/src/main/resources/slack-appender-dev.xml
module-batch/src/main/resources/slack-appender-prod.xml
module-common/build.gradle

- Slack 알림 전송 기능 구현
- 검색 키워드 길이 제한 validation 추가

3월 3주차 수시배포 3

---

module-common/build.gradle

- 전체 원티드 JD 스크래핑 후 마감된 JD 정보 반영 기능 구현

3월 3주차 수시배포

---

module-api/src/test/java/kernel/jdon/moduleapi/domain/favorite/presentation/FavoriteControllerIntegrationTest.java
module-domain/src/main/java/kernel/jdon/moduledomain/jobcategory/domain/JobCategory.java

- NotNull 조건이 추가됨에 따라, member를 모킹할 때 JobCategory를 생성해서 추가했습니다.
- 빌더 추가했습니다.
- JobCategory를 빌더로 생성한 후 Member의 builder에 추가했습니다.
- closes: #563 
---
어떤 변경 사항이 있나요?

BugFix: NotNull 조건 추가로 통합테스트 에러 해결

---

module-api/src/main/java/kernel/jdon/moduleapi/domain/coffeechat/infrastructure/CoffeeChatRepositoryImpl.java

- 커피챗 테이블을 풀스캔하던 목록조회 쿼리를 1.커버링 인덱스를 사용하는 id조회 쿼리와 2. 조회된 id 기준으로 content를 조회하는 쿼리로 분리하여 개선했습니다.
- [커버링 인덱스](https://jojoldu.tistory.com/529?category=637935) 사용을 위해 아래 두가지 복합 인덱스를 생성했습니다.
- is_deleted, created_date, id
- is_deleted, created_by 
- title 검색조건이 없는 경우에 한해 개선되었으며, 추후 title검색 조건이 있는 경우까지 고려하여 개선이 필요합니다.
- 컨텐츠 조회쿼리
- 약 2.1~2.2초 소요
- 카운트 쿼리
- 약 1.6초 소요
- 컨텐츠 조회 쿼리와 카운트 쿼리 모두 type열이 ALL로 풀스캔
- 총 소요시간 약 3.7~3.8초
id 조회쿼리와 카운트 쿼리에서 커버링 인덱스 사용을 위해 복합 인덱스를 생성했습니다.
- id 조회 쿼리
key에 새로 생성한 인덱스 적용 확인, extra열에 using index로 보아 커버링 인덱스 확인
- 컨텐츠 조회 쿼리
pk인 id를 기준으로 in절로 비교하기에 type열에 range key에 PRIMARY 적용
- 카운트 쿼리
key에 새로 생성한 인덱스 적용 확인, extra열에 using index로 보아 커버링 인덱스 확인
- id 조회 쿼리
- ![image](https://github.com/Kernel360/f1-JDON-Backend/assets/111513287/6d28d3c8-7257-4f1e-b103-a1523f01eb10)
- …

Refactor: 커버링 인덱스를 활용하도록 쿼리 분리

---

module-api/src/main/resources/application-dev.yml

부하 테스트 시 HikariCP 사이즈가 성능에 영향을 미치는 것으로 보여 사이즈를 조정하면서 최적값을 찾고자 합니다.
HikariCP 사이즈를 20으로 변경했습니다.
- closes: #581 
---
어떤 변경 사항이 있나요?

Fix: 커넥션풀 사이즈 20으로 조정

---

module-api/src/main/resources/application-dev.yml

부하 테스트 시 HikariCP 사이즈가 성능에 영향을 미치는 것으로 보여 사이즈를 조정하면서 최적값을 찾고자 합니다.
HikariCP 사이즈를 30으로 변경했습니다.
- closes: #583 
---
어떤 변경 사항이 있나요?

Fix: 커넥션풀 사이즈 30으로 조정
